/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'TACP4'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct __attribute__((aligned(2))) mapunit_dat
{
  __int16 strenght;
  __int16 Explosion_Power_at_GZ;
  __int16 Explosion_depletion_rate;
  __int16 Explosion_Type;
  char fire_resistance;
  char burn_time;
  char intensity_time_table;
  char blockage_phisical;
  char blockage_gas;
  char blockage_fire;
  char blockage_psionic;
  char lof1_0;
  char lof1_1;
  char lof1_2;
  char lof1_3;
  char lof1_4;
  char lof1_5;
  char lof1_6;
  char lof1_7;
  char lof1_8;
  char lof1_9;
  char lof1_10;
  char lof1_11;
  char lof1_12;
  char lof1_13;
  char lof1_14;
  char lof1_15;
  char lof1_16;
  char lof1_17;
  char lof1_18;
  char lof1_19;
  char lof2_1;
  char lof2_2;
  char lof2_3;
  char lof2_4;
  char lof2_5;
  char lof2_6;
  char lof2_7;
  char lof2_8;
  char lof2_9;
  char lof2_10;
  char lof2_11;
  char lof2_12;
  char lof2_13;
  char lof2_14;
  char lof2_15;
  char lof2_16;
  char lof2_17;
  char lof2_18;
  char lof2_19;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char tile_size;
  char field_3B;
  __int16 damaged_tile_index;
  __int16 index_anim;
  char Number_of_animated_frames;
  char Auto_loop_;
  char Transparent;
  char sound_effects;
  char Door_flag;
  char Closed_door;
  char LOS_Through_Terrain;
  char Floor_marker;
  char Gravlift;
  char field_49;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char field_4E;
  char Movement_cost;
  char Climbable;
  char Object_height;
  char Floating_object;
  char Provides_support;
  char Gets_support_from;
  char Independent_structure;
};

/* 2 */
struct prog_img
{
  char field_0[9];
};

/* 3 */
struct proj_offs
{
  char field_0[36];
};

/* 5 */
#pragma pack(push, 1)
struct struc_1
{
  __int16 field_0;
  __int16 group_number;
  __int16 field_4;
  int track_number;
};
#pragma pack(pop)

/* 6 */
#pragma pack(push, 1)
struct struct_0
{
  __int16 field_0;
  char gap_2[18];
  void *anonymous_1;
  __int16 anonymous_2;
  char gap_1A[3];
  char anonymous_3;
  char field_1E;
  char field_1F;
};
#pragma pack(pop)

/* 7 */
struct __attribute__((aligned(4))) struct_sound
{
  char name[50];
  __attribute__((packed)) __attribute__((aligned(1))) int bitrate;
  __attribute__((packed)) __attribute__((aligned(1))) int anonymous_1;
  __int16 format;
  int anonymous_2;
};

/* 8 */
struct agent_save_struct;

/* 9 */
struct __attribute__((aligned(2))) agent_init_struc
{
  char score;
  char field_1;
  char speed;
  char max_speed_increese;
  __int16 health;
  __int16 max_health_increase;
  char unk1;
  char unk2;
  char stamina;
  char max_stamina_increase;
  char reaction;
  char max_reaction_increase;
  char strenght;
  char max_strenght_increase;
  char braverly;
  char max_braverly_increase;
  char psi_energy;
  char max_psi_energy_increase;
  char psi_attack;
  char max_psi_attack_incriase;
  char psi_defece;
  char max_psi_defece_incriace;
  char field_24;
  char field_25;
  char accuracy;
  char max_accuracy_incriace;
  char field_28;
  char field_30;
  char field_31;
  char field_32;
  char bio_skill;
  char max_bio_skill_increace;
  char qua_skill;
  char max_qua_skill_increace;
  char eng_skill;
  char max_eng_skill_increace;
  char field_38;
  char field_39;
  char field_40;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  __int16 size_x;
  __int16 size_y;
  __int16 field_64;
  char movement_type;
  char field_67;
  char inventory;
  char leg_type;
  __int16 leg_armor;
  __int16 body_armor;
  __int16 r_arm_armor;
  __int16 l_arm_armor;
  __int16 head_armor;
  __int16 unk_armor;
  char unknown_71;
  char equipment_set_1;
  char equipment_set_2;
  char equipment_set_3;
  char equipment_set_4;
  char equipment_set_5;
  __int16 damage_modifier_group;
  __int16 unknown_78;
  __int16 empty_slot_flag;
  char assigment_type;
  char field_5F;
  __int16 image_position_1;
  __int16 image_position_2;
  __int16 image_position_3;
  __int16 image_position_4;
  __int16 image;
};

/* 10 */
struct __attribute__((aligned(2))) CITYMAP_DAT
{
  char tile_type;
  char road_type;
  char road_junction[4];
  char road_level_change[4];
  char height;
  char constitution;
  char value;
  char overlaytile_idx;
  char landing_pad;
  char walk_type;
  char voxelIdx[16];
  char has_basement;
  char people_tube_connections[6];
  char mass;
  __int16 strength;
  __int16 damagedtile_idx;
  __int16 supportile_idx;
  char target_Pnt[4];
  __int16 stratmap_idx;
};

/* 11 */
#pragma pack(push, 1)
struct press_button
{
  int scan_mous;
  int img_unprs;
  int img_aim;
  int x_top;
  int y_top;
  int x_botn;
  int y_botn;
  int img_flag;
  int unkn1;
  __int16 scan_keybr;
  __int16 unkn2;
  __int16 unkn3;
  int scan_mouse;
  int tooltip;
  __int16 press_flag;
};
#pragma pack(pop)

/* 12 */
struct craft_weapon_data
{
  __int16 prog_speed;
  __int16 prog_image;
  __int16 damage;
  __int16 accuracy;
  __int16 fire_delay;
  __int16 tail_size;
  __int16 guided;
  __int16 turn_rate;
  __int16 range;
  __int16 projectile_lifetime;
  __int16 horizontal_firing_arc;
  __int16 vertical_firing_arc;
  __int16 point_defence;
  __int16 splits_in_projectile;
  __int16 firing_sound;
  __int16 impact_sound;
  __int16 explosion_graphic;
};

/* 13 */
struct __attribute__((aligned(2))) vehicle_equipment_1
{
  char item_type;
  char effect;
  __int16 item_group;
  __int16 weight;
  __int16 max_ammo_fuel;
  __int16 ammo_fuel_type_used;
  __int16 ammo_fuel_consumptio;
  __int16 picture;
  char size_x;
  char size_y;
  __int16 unknown_11;
  __int16 unknown_12;
  __int16 manufacturer;
  __int16 storage_space_needed;
};

/* 14 */
struct research_struc
{
  char lab_size_required;
  char item_prerequisite_modifier;
  char tech_prerequisite_modifier;
  char item_prerequisite_group1;
  char item_prerequisite_group2;
  char item_prerequisite_group3;
  __int16 item_prerequisite1;
  __int16 item_prerequisite2;
  __int16 item_prerequisite3;
  __int16 tech_prerequisite_1;
  __int16 tech_prerequisite_2;
  __int16 tech_prerequisite_3;
  __int16 score;
  int skill_hours;
  char research_group;
  char UFOPadia_group;
  __int16 UFOpedia_entry;
};

/* 15 */
#pragma pack(push, 1)
struct craft_engine_data
{
  int engine_power;
  __int16 top_speed;
};
#pragma pack(pop)

/* 16 */
#pragma pack(push, 1)
struct vehicle_equipment_3_3
{
  __int16 accuracy_modifier;
  __int16 cargo_space;
  __int16 passengers;
  __int16 aliens_held;
  __int16 missile_jamming;
  __int16 shielding;
  __int16 cloaking;
  __int16 teleporting;
  __int16 dimension_shifting;
};
#pragma pack(pop)

/* 17 */
struct __attribute__((aligned(2))) sound_buff
{
  __int16 num;
  __int16 unknown1;
  __int16 a5;
  __int16 anon3;
  __int16 FFFF_1;
  __int16 channel;
  __int16 a3;
  __int16 a4;
  __int16 FFFF_2;
};

/* 18 */
struct __attribute__((packed)) __attribute__((aligned(2))) manufac_data
{
  __int16 manufacturable;
  int skill_hours;
  __int16 unused1;
  __int16 unused2;
  __int16 tech_prerequisite_modifier;
  __int16 tech_prerequisite_1;
  __int16 tech_prerequisite_2;
  int tech_prerequisite_3;
  char part_need_to_build_item;
  char unused10;
  int unused11;
  __int16 unused12;
  int unused13;
  int unused14;
  int unused15;
  int manufac_cost;
  __int16 item_group;
  __int16 item;
  __int16 lab_size_required;
};

/* 19 */
struct __attribute__((packed)) __attribute__((aligned(2))) veh_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  __int16 current_stock;
  __int16 field_10;
  int last_week_amount_for_sale;
};

/* 20 */
struct __attribute__((packed)) __attribute__((aligned(2))) craft_equip_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 21 */
enum font
{
  smalfont = 0x0,
  smallset = 0x1,
  bigfont = 0x2,
};

/* 22 */
struct __attribute__((packed)) __attribute__((aligned(2))) amo_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 23 */
struct __attribute__((packed)) __attribute__((aligned(2))) agent_eqv_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 24 */
struct __attribute__((packed)) __attribute__((aligned(2))) funds_init
{
  __int16 race;
  int org_member;
  char Security_level;
  char Security_number;
  int balance;
  int external_income;
  char rebuildrate;
  char like_alien;
};

/* 25 */
struct facility_data_t;

/* 26 */
struct __attribute__((aligned(2))) projectile_stru
{
  __int16 weapon_type;
  __int16 prog_image;
  __int16 prog_speed;
  __int16 x_pos[50];
  __int16 y_pos[50];
  __int16 z_pos[50];
  __int16 field_132;
  __int16 proj_number;
  __int16 tail_size_;
  __int16 was_used;
  __int16 num_aiming_unit;
  __int16 dist_3d;
  __int16 x_y_vs_z1_x2;
  __int16 x_y_vs_z2_x2;
  __int16 z_shift_1;
  __int16 z_direct;
  __int16 z_shift_2;
  __int16 field_148;
  __int16 distance;
  __int16 anglex2;
  __int16 distx2;
  __int16 r_l_direct;
  __int16 up_down;
  __int16 direct_x;
  __int16 direct_y;
  __int16 projectile_lifetime;
  __int16 unit_owner_struc;
  __int16 field_15C;
};

/* 27 */
struct proj_color
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
};

/* 28 */
struct projectile_img
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  char field_22;
  char field_23;
};

/* 29 */
struct vehicle_equipment_layout
{
  __int16 amount_slots;
  char slot_1_x_pos;
  char slot_1_y_pos;
  char slot_1_x_size;
  char slot_1_y_size;
  char slot_1_type;
  char slot_1_safe_flag;
  char safe_1_x_centr;
  char safe_1_y_centr;
  char slot_2_x_pos;
  char slot_2_y_pos;
  char slot_2_x_size;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  __int16 field_22;
  char field_24;
  char field_25;
  char field_26;
  char field_27;
  char field_28;
  char field_29;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char field_30;
  char field_31;
  char field_32;
  char field_33;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char field_3E;
  char field_3F;
  char field_40;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char field_4E;
  char field_4F;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  char field_5A;
  char field_5B;
  char field_5C;
  char field_5D;
  char field_5E;
  char field_5F;
  char field_60;
  char field_61;
  char field_62;
  char field_63;
  char field_64;
  char field_65;
  char field_66;
  char field_67;
  char field_68;
  char field_69;
  char field_6A;
  char field_6B;
  char field_6C;
  char field_6D;
  char field_6E;
  char field_6F;
  char field_70;
  char field_71;
  char field_72;
  char field_73;
  char field_74;
  char field_75;
  char field_76;
  char field_77;
  char field_78;
  char field_79;
  char field_7A;
  char field_7B;
  __int16 field_7C;
  char field_7E;
  char field_7F;
  char field_80;
  char field_81;
  char field_82;
  char field_83;
  char field_84;
  char field_85;
  char field_86;
  char field_87;
  char field_88;
  char field_89;
  char field_8A;
  char field_8B;
  char field_8C;
  char field_8D;
  char field_8E;
  char field_8F;
  char field_90;
  char field_91;
  char field_92;
  char field_93;
  char field_94;
  char field_95;
  char field_96;
  char field_97;
  char field_98;
  char field_99;
  char field_9A;
  char field_9B;
  char field_9C;
  char field_9D;
  char field_9E;
  char field_9F;
  char field_A0;
  char field_A1;
  char field_A2;
  char field_A3;
  char field_A4;
  char field_A5;
  char field_A6;
  char field_A7;
  char field_A8;
  char field_A9;
  char field_AA;
  char field_AB;
  char field_AC;
  char field_AD;
  char field_AE;
  char field_AF;
  char field_B0;
  char field_B1;
  char field_B2;
  char field_B3;
  char field_B4;
  char field_B5;
  char field_B6;
  char field_B7;
  char field_B8;
  char field_B9;
  char field_BA;
  char field_BB;
  char field_BC;
  char field_BD;
  char field_BE;
  char field_BF;
  char field_C0;
  char field_C1;
  char field_C2;
  char field_C3;
  char field_C4;
  char field_C5;
  char field_C6;
  char field_C7;
  char field_C8;
  char field_C9;
  char field_CA;
  char field_CB;
  char field_CC;
  char field_CD;
  char field_CE;
  char field_CF;
  __int16 field_D0;
  char field_D2;
  char field_D3;
  char field_D4;
  char field_D5;
  char field_D6;
  char field_D7;
  char field_D8;
  char field_D9;
  char field_DA;
  char field_DB;
  char field_DC;
  char field_DD;
  char field_DE;
  char field_DF;
  char field_E0;
  char field_E1;
  char field_E2;
  char field_E3;
  char field_E4;
  char field_E5;
  char field_E6;
  char field_E7;
  char field_E8;
  char field_E9;
  char field_EA;
  char field_EB;
  char field_EC;
  char field_ED;
  char field_EE;
  char field_EF;
  char field_F0;
  char field_F1;
  char field_F2;
  char field_F3;
  char field_F4;
  char field_F5;
  char field_F6;
  char field_F7;
  char field_F8;
  char field_F9;
  char field_FA;
  char field_FB;
  char field_FC;
  char field_FD;
  char field_FE;
  char field_FF;
  char field_100;
  char field_101;
  char field_102;
  char field_103;
  char field_104;
  char field_105;
  char field_106;
  char field_107;
  char field_108;
  char field_109;
  char field_10A;
  char field_10B;
  char field_10C;
  char field_10D;
  char field_10E;
  char field_10F;
  char field_110;
  char field_111;
  char field_112;
  char field_113;
  char field_114;
  char field_115;
  char field_116;
  char field_117;
  char field_118;
  char field_119;
  char field_11A;
  char field_11B;
  char field_11C;
  char field_11D;
  char field_11E;
  char field_11F;
  char field_120;
  char field_121;
  char field_122;
  char field_123;
  char field_124;
  char field_125;
  char field_126;
  char field_127;
  char field_128;
  char field_129;
  char field_12A;
  char field_12B;
  char field_12C;
  char field_12D;
  char field_12E;
  char field_12F;
  char field_130;
  char field_131;
  char field_132;
  char field_133;
  char field_134;
  char field_135;
  char field_136;
  char field_137;
  char field_138;
  char field_139;
  char field_13A;
  char field_13B;
  char field_13C;
  char field_13D;
  char field_13E;
  char field_13F;
  char field_140;
  char field_141;
  char field_142;
  char field_143;
  char field_144;
  char field_145;
  char field_146;
  char field_147;
  char field_148;
  char field_149;
  char field_14A;
  char field_14B;
  char field_14C;
  char field_14D;
  char field_14E;
  char field_14F;
  char field_150;
  char field_151;
  char field_152;
  char field_153;
  char field_154;
  char field_155;
  char field_156;
  char field_157;
  char field_158;
  char field_159;
  char field_15A;
  char field_15B;
  char field_15C;
  char field_15D;
  char field_15E;
  char field_15F;
  char field_160;
  char field_161;
  char field_162;
  char field_163;
  char field_164;
  char field_165;
  char field_166;
  char field_167;
  char field_168;
  char field_169;
};

/* 30 */
struct unit_score_req
{
  int level_2;
  int level_3;
  int level_4;
  int level_5;
  int level_6;
  int level_7;
  int level_8;
};

/* 31 */
struct equip_hard_evel
{
  int novice;
  int easy;
  int medium;
  int hard;
  int superhuman;
};

/* 32 */
struct __attribute__((aligned(2))) damage_modif
{
  __int16 smoke;
  __int16 anti_alien_gas;
  __int16 incendiary;
  __int16 stun_gas;
  __int16 explosive;
  __int16 stun;
  __int16 psionic_blast;
  __int16 armor_piercing;
  __int16 laser_beam;
  __int16 plasma;
  __int16 toxin_A;
  __int16 toxin_B;
  __int16 toxin_C;
  __int16 dimesion_destabiliser;
  __int16 disruptor_beam;
  __int16 explosive1;
  __int16 entropy_enzyme;
  __int16 falling_object;
};

/* 33 */
struct stru_relations_save
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_34;
  int field_38;
  int field_3C;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
  int field_68;
  int field_6C;
};

/* 34 */
struct paed_struct
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
};

/* 35 */
struct blding_struc_save
{
  __int16 building_name;
  __int16 x1position;
  __int16 x2position;
  __int16 y1position;
  __int16 y2position;
  __int16 field_A;
  __int16 count_value_zero_tile;
  __int16 x_pad_pos;
  __int16 y_pad_pos;
  __int16 z_pad_pos;
  __int16 field_14;
  __int16 field_16;
  __int16 field_18;
  __int16 field_1A;
  __int16 field_1C;
  __int16 field_1E;
  __int16 field_20;
  __int16 field_22;
  __int16 field_24;
  __int16 field_26;
  __int16 field_28;
  __int16 field_2A;
  __int16 field_2C;
  __int16 field_2E;
  __int16 field_30;
  __int16 unknown26;
  __int16 field_34;
  __int16 field_36;
  __int16 field_38;
  __int16 field_3A;
  __int16 field_3C;
  __int16 field_3E;
  __int16 field_40;
  __int16 field_42;
  __int16 field_44;
  __int16 field_46;
  __int16 field_48;
  __int16 field_4A;
  __int16 field_4C;
  __int16 field_4E;
  __int16 field_50;
  __int16 field_52;
  __int16 field_54;
  __int16 field_56;
  __int16 field_58;
  __int16 field_5A;
  __int16 field_5C;
  __int16 field_5E;
  __int16 field_60;
  __int16 unknown50;
  __int16 unknow51;
  __int16 field_66;
  __int16 field_68;
  __int16 field_6A;
  __int16 field_6C;
  __int16 field_6E;
  __int16 field_70;
  __int16 field_72;
  __int16 field_74;
  __int16 field_76;
  __int16 field_78;
  __int16 field_7A;
  __int16 field_7C;
  __int16 field_7E;
  __int16 field_80;
  __int16 field_82;
  __int16 field_84;
  __int16 field_86;
  __int16 field_88;
  __int16 field_8A;
  __int16 field_8C;
  __int16 field_8E;
  __int16 field_90;
  __int16 field_92;
  __int16 field_94;
  __int16 unknown76;
  __int16 field_98;
  __int16 field_9A;
  __int16 field_9C;
  __int16 field_9E;
  __int16 field_A0;
  __int16 field_A2;
  __int16 field_A4;
  __int16 field_A6;
  __int16 junction;
  __int16 bld_function;
  __int16 bld_type;
  __int16 field_AE;
  __int16 field_B0;
  __int16 field_B2;
  __int16 field_B4;
  __int16 purchaseable;
  __int16 field_B8;
  __int16 price;
  __int16 alien_detection_timout;
  __int16 fixed_costs;
  __int16 maximum_workforce;
  __int16 current_workforce;
  __int16 current_wage;
  __int16 Income_per_capita;
  char owner;
  char field_C9;
  char field_CA;
  char field_CB;
  char $$needed;
  char respect;
  __int16 field_CE;
  __int16 field_D0;
  __int16 field_D2;
  char alien_eggs;
  char brainsuckers;
  char multiworm;
  char hyperworm;
  char chrystali;
  char anthropods;
  char skeletoids;
  char spitter;
  char poppers;
  char megaspawn;
  char psimorphs;
  char quinspawn;
  char micronoid_aggregate;
  char brainsuckers_pods;
};

/* 36 */
struct __attribute__((packed)) __attribute__((aligned(2))) funds_struc_save
{
  __int16 race;
  int org_member;
  char Security_level;
  char Security_number;
  int balance;
  int external_income;
  char rebuildrate;
  char like_alien;
  __int16 combat_value;
  __int16 bld_count;
  int fund_history52;
  int fund_history51;
  int fund_history50;
  int fund_history49;
  int fund_history48;
  int fund_history47;
  int fund_history46;
  int fund_history45;
  int fund_history44;
  int fund_history43;
  int fund_history42;
  int fund_history41;
  int fund_history40;
  int fund_history39;
  int fund_history38;
  int fund_history37;
  int fund_history36;
  int fund_history35;
  int fund_history34;
  int fund_history33;
  int fund_history32;
  int fund_history31;
  int fund_history30;
  int fund_history29;
  int fund_history28;
  int fund_history27;
  int fund_history26;
  int fund_history25;
  int fund_history24;
  int fund_history23;
  int fund_history22;
  int fund_history21;
  int fund_history20;
  int fund_history19;
  int fund_history18;
  int fund_history17;
  int fund_history16;
  int fund_history15;
  int fund_history14;
  int fund_history13;
  int fund_history12;
  int fund_history11;
  int fund_history10;
  int fund_history9;
  int fund_history8;
  int fund_history7;
  int fund_history6;
  int fund_history5;
  int fund_history4;
  int fund_history3;
  int fund_history2;
  int fund_history;
  int funding_history52;
  int funding_history51;
  int funding_history50;
  int funding_history49;
  int field_F6;
  int field_FA;
  int field_FE;
  int field_102;
  int field_106;
  int field_10A;
  int field_10E;
  int field_112;
  int field_116;
  int field_11A;
  int field_11E;
  int field_122;
  int field_126;
  int field_12A;
  int field_12E;
  int field_132;
  int field_136;
  int field_13A;
  int field_13E;
  int field_142;
  int field_146;
  int field_14A;
  int field_14E;
  int field_152;
  int field_156;
  int field_15A;
  int field_15E;
  int field_162;
  int field_166;
  int field_16A;
  int field_16E;
  int field_172;
  int field_176;
  int field_17A;
  int field_17E;
  int field_182;
  int field_186;
  int field_18A;
  int field_18E;
  int field_192;
  int field_196;
  int field_19A;
  int field_19E;
  int field_1A2;
  int field_1A6;
  int field_1AA;
  int field_1AE;
  int cur_funds;
};

/* 37 */
struct vehicle_init_data
{
  __int16 manufacturer;
  __int16 movement_type;
  __int16 animation_type;
  __int16 size_x;
  __int16 size_y;
  __int16 size_z;
  __int16 image_pos_1;
  __int16 image_pos_2;
  __int16 image_pos_3;
  __int16 image_pos_4;
  __int16 image;
  __int16 built_in_accelerat;
  __int16 built_in_unknown;
  __int16 built_in_top_speed;
  __int16 shadow_image;
  __int16 shadow_image_pos_1;
  __int16 shadow_image_pos_2;
  __int16 shadow_image_pos_3;
  __int16 shadow_image_pos_4;
  __int16 loftemps_height;
  __int16 loftemps_index;
  __int16 unknown22;
  __int16 unused23;
  __int16 constitution;
  __int16 crash_constitution;
  __int16 weight;
  __int16 rear_armor;
  __int16 top_armor;
  __int16 right_armor;
  __int16 left_armor;
  __int16 under_armor;
  __int16 front_armor;
  __int16 passengers;
  __int16 agressivenes;
  __int16 score;
  char equip_layout;
  char equip_layout_image[8];
  char unused38;
  char unknown39;
  char equip_slot[45];
};

/* 38 */
union __attribute__((aligned(8))) __m64
{
  unsigned __int64 m64_u64;
  float m64_f32[2];
  char m64_i8[8];
  __int16 m64_i16[4];
  int m64_i32[2];
  __int64 m64_i64;
  unsigned __int8 m64_u8[8];
  unsigned __int16 m64_u16[4];
  unsigned int m64_u32[2];
};

/* 39 */
union __attribute__((aligned(16))) __m128
{
  float m128_f32[4];
  unsigned __int64 m128_u64[2];
  char m128_i8[16];
  __int16 m128_i16[8];
  int m128_i32[4];
  __int64 m128_i64[2];
  unsigned __int8 m128_u8[16];
  unsigned __int16 m128_u16[8];
  unsigned int m128_u32[4];
};

/* 40 */
struct __m128d
{
  double m128d_f64[2];
};

/* 41 */
union __attribute__((aligned(16))) __m128i
{
  char m128i_i8[16];
  __int16 m128i_i16[8];
  int m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned int m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

/* 42 */
struct ufo_missions
{
  __int16 ufo_type_1;
  __int16 ufo_type_2;
  __int16 ufo_type_3;
  __int16 ufo_type_1_amount;
  __int16 ufo_type_2_amount;
  __int16 ufo_type_3_amount;
  __int16 ufo_type_1_mission;
  __int16 ufo_type_2_mission;
  __int16 ufo_type_3_mission;
  __int16 ufo_type_1_escorts;
  __int16 ufo_type_2_escorts;
  __int16 ufo_type_3_escorts;
  __int16 field_18;
  __int16 field_1A;
  __int16 field_1C;
  __int16 field_1E;
  __int16 field_20;
  __int16 field_22;
  __int16 field_24;
  __int16 field_26;
  __int16 field_28;
};

/* 43 */
struct ufos_grow
{
  __int16 probe;
  __int16 scout;
  __int16 transport;
  __int16 fast_attack_ship;
  __int16 destroyer;
  __int16 assault_ship;
  __int16 bomber;
  __int16 escort;
  __int16 battleship;
  __int16 mothership;
};

/* 44 */
struct __attribute__((aligned(2))) score_equip_set
{
  __int16 weapon_1;
  __int16 clip_type_1;
  __int16 clip_amount_1;
  __int16 weapon_2;
  __int16 clip_type_2;
  __int16 clip_amount_2;
  __int16 weapon_3;
  __int16 clip_type_3;
  __int16 clip_amount_3;
  __int16 weapon_4;
  __int16 clip_type_4;
  __int16 clip_amount_4;
  __int16 weapon_5;
  __int16 clip_type_5;
  __int16 clip_amount_5;
  __int16 weapon_6;
  __int16 clip_type_6;
  __int16 clip_amount_6;
  __int16 weapon_7;
  __int16 clip_type_7;
  __int16 clip_amount_7;
  __int16 weapon_8;
  __int16 clip_type_8;
  __int16 clip_amount_8;
  __int16 weapon_9;
  __int16 clip_type_9;
  __int16 clip_amount_9;
  __int16 weapon_10;
  __int16 clip_type_10;
  __int16 clip_amount_10;
  __int16 grenade_type1;
  __int16 grenade_amount1;
  __int16 grenade_type2;
  __int16 grenade_amount2;
  __int16 grenade_type3;
  __int16 grenade_amount3;
  __int16 grenade_type4;
  __int16 grenade_amount4;
  __int16 grenade_type5;
  __int16 grenade_amount5;
  __int16 grenade_type6;
  __int16 grenade_amount6;
  __int16 grenade_type7;
  __int16 grenade_amount7;
  __int16 grenade_type8;
  __int16 grenade_amount8;
  __int16 grenade_type9;
  __int16 grenade_amount9;
  __int16 grenade_type10;
  __int16 grenade_amount10;
  __int16 other_equp_1;
  __int16 other_equp_2;
  __int16 other_equp_3;
  __int16 other_equp_4;
  __int16 other_equp_5;
  __int16 other_equp_6;
  __int16 other_equp_7;
  __int16 other_equp_8;
  __int16 other_equp_9;
  __int16 other_equp_10;
  __int16 other_equp_11;
  __int16 other_equp_12;
  __int16 other_equp_13;
  __int16 other_equp_14;
  __int16 other_equp_15;
  __int16 other_equp_16;
  __int16 other_equp_17;
  __int16 other_equp_18;
  __int16 other_equp_19;
  __int16 other_equp_20;
};

/* 45 */
struct org_names
{
  __int16 field_0[25];
};

/* 46 */
typedef __iobuf FILE;

/* 47 */
struct relation_struc
{
  char X_COM;
  char Alien;
  char Government;
  char Megapol;
  char CultofSirius;
  char Marsec;
  char Superdynamics;
  char General_Metro;
  char Cyberweb;
  char Transtellar;
  char Solmine;
  char Sensovision;
  char Lifetree;
  char Nutrivend;
  char Evonet;
  char Sanctuary_Clinic;
  char Nanotech;
  char Energen;
  char Synthemesh;
  char Gravball_League;
  char Psyke;
  char Diablo;
  char Osiron;
  char SELF;
  char Mutant_Alliance;
  char Extropians;
  char Technocrats;
  char Civilian;
};

/* 48 */
struct ufo_objects
{
  int portal_home;
  __int16 portal_x_coord_1;
  __int16 portal_x_coord_2;
  __int16 portal_x_coord_3;
  __int16 portal_x_coord_4;
  __int16 portal_x_coord_5;
  __int16 portal_x_coord_6;
  __int16 portal_x_coord_7;
  __int16 portal_x_coord_8;
  __int16 portal_x_coord_9;
  __int16 portal_x_coord_10;
  __int16 portal_y_coord_1;
  __int16 portal_y_coord_2;
  __int16 portal_y_coord_3;
  __int16 portal_y_coord_4;
  __int16 portal_y_coord_5;
  __int16 portal_y_coord_6;
  __int16 portal_y_coord_7;
  __int16 portal_y_coord_8;
  __int16 portal_y_coord_9;
  __int16 portal_y_coord_10;
  __int16 portal_z_coord_1;
  __int16 portal_z_coord_2;
  __int16 portal_z_coord_3;
  __int16 portal_z_coord_4;
  __int16 portal_z_coord_5;
  __int16 portal_z_coord_6;
  __int16 portal_z_coord_7;
  __int16 portal_z_coord_8;
  __int16 portal_z_coord_9;
  __int16 portal_z_coord_10;
  __int16 field_40;
  __int16 field_42;
  __int16 field_44;
  __int16 field_46;
  __int16 field_48;
  __int16 field_4A;
  __int16 field_4C;
  __int16 field_4E;
  __int16 field_50;
  __int16 field_52;
  __int16 field_54;
  __int16 field_56;
  __int16 field_58;
  __int16 field_5A;
  __int16 field_5C;
  __int16 field_5E;
  __int16 field_60;
  __int16 field_62;
  __int16 field_64;
  __int16 field_66;
  __int16 field_68;
  __int16 field_6A;
  __int16 field_6C;
  __int16 field_6E;
  __int16 field_70;
  __int16 field_72;
  __int16 field_74;
  __int16 field_76;
  __int16 field_78;
  __int16 field_7A;
  __int16 field_7C;
  __int16 field_7E;
  __int16 field_80;
  __int16 field_82;
  __int16 field_84;
  __int16 field_86;
  __int16 field_88;
  __int16 field_8A;
  __int16 prob;
  __int16 scout;
  __int16 transp;
  __int16 fast_ship;
  __int16 destroyer;
  __int16 assault_ship;
  __int16 bomber;
  __int16 escort;
  __int16 battlship;
  __int16 mothership;
  __int16 field_A0;
  __int16 field_A2;
  __int16 field_A4;
  __int16 field_A6;
  __int16 field_A8;
  __int16 field_AA;
  __int16 field_AC;
  __int16 field_AE;
  __int16 field_B0;
  __int16 field_B2;
  __int16 field_B4;
  __int16 field_B6;
  __int16 field_B8;
  __int16 field_BA;
  __int16 field_BC;
  __int16 field_BE;
  __int16 field_C0;
  __int16 field_C2;
  __int16 field_C4;
  __int16 field_C6;
  __int16 field_C8;
  __int16 field_CA;
  __int16 field_CC;
  __int16 field_CE;
  __int16 field_D0;
  __int16 field_D2;
  __int16 field_D4;
  __int16 field_D6;
  __int16 field_D8;
  __int16 field_DA;
  __int16 field_DC;
  __int16 field_DE;
  __int16 field_E0;
  __int16 field_E2;
  __int16 field_E4;
  __int16 field_E6;
  __int16 field_E8;
  __int16 field_EA;
  __int16 field_EC;
  __int16 field_EE;
  __int16 field_F0;
  __int16 field_F2;
  __int16 field_F4;
  __int16 field_F6;
  __int16 field_F8;
  __int16 field_FA;
  __int16 field_FC;
  __int16 field_FE;
  __int16 field_100;
  __int16 field_102;
  __int16 field_104;
  __int16 field_106;
  __int16 field_108;
  __int16 field_10A;
  __int16 field_10C;
  __int16 field_10E;
  __int16 field_110;
  __int16 field_112;
  __int16 field_114;
  __int16 field_116;
  __int16 field_118;
  __int16 field_11A;
  __int16 field_11C;
  __int16 field_11E;
  __int16 field_120;
  __int16 field_122;
  __int16 field_124;
  __int16 field_126;
  __int16 field_128;
  __int16 field_12A;
  __int16 field_12C;
  __int16 field_12E;
  __int16 field_130;
  __int16 field_132;
  __int16 field_134;
  __int16 field_136;
  __int16 field_138;
  __int16 field_13A;
  __int16 field_13C;
  __int16 field_13E;
  __int16 field_140;
  __int16 field_142;
  __int16 field_144;
  __int16 field_146;
  __int16 field_148;
  __int16 field_14A;
  __int16 field_14C;
  __int16 field_14E;
  __int16 field_150;
  __int16 field_152;
  __int16 field_154;
  __int16 field_156;
  __int16 field_158;
  __int16 field_15A;
  __int16 field_15C;
  __int16 field_15E;
  __int16 field_160;
  __int16 field_162;
  __int16 field_164;
  __int16 field_166;
  __int16 field_168;
  __int16 field_16A;
  __int16 field_16C;
  __int16 field_16E;
  __int16 field_170;
  __int16 field_172;
  __int16 field_174;
  __int16 field_176;
  __int16 field_178;
  __int16 field_17A;
  __int16 field_17C;
  __int16 field_17E;
  __int16 field_180;
  __int16 field_182;
  __int16 field_184;
  __int16 field_186;
  __int16 field_188;
  __int16 field_18A;
  __int16 field_18C;
  __int16 field_18E;
  __int16 field_190;
  __int16 field_192;
  __int16 field_194;
  __int16 field_196;
  __int16 field_198;
  __int16 field_19A;
  __int16 field_19C;
  __int16 field_19E;
  __int16 field_1A0;
  __int16 field_1A2;
  __int16 field_1A4;
  __int16 field_1A6;
  __int16 field_1A8;
  __int16 field_1AA;
  __int16 field_1AC;
  __int16 field_1AE;
  __int16 field_1B0;
  __int16 field_1B2;
  __int16 field_1B4;
  __int16 field_1B6;
  __int16 field_1B8;
  __int16 field_1BA;
  __int16 field_1BC;
  __int16 field_1BE;
  __int16 field_1C0;
  __int16 field_1C2;
  __int16 field_1C4;
  __int16 field_1C6;
  __int16 field_1C8;
  __int16 field_1CA;
  __int16 field_1CC;
  __int16 field_1CE;
  __int16 field_1D0;
  __int16 field_1D2;
  __int16 field_1D4;
  __int16 field_1D6;
  __int16 field_1D8;
  __int16 field_1DA;
  __int16 field_1DC;
  __int16 field_1DE;
  __int16 field_1E0;
  __int16 field_1E2;
  __int16 field_1E4;
  __int16 field_1E6;
  __int16 field_1E8;
  __int16 field_1EA;
  __int16 field_1EC;
  __int16 field_1EE;
  __int16 field_1F0;
  __int16 field_1F2;
  __int16 field_1F4;
  __int16 field_1F6;
  __int16 field_1F8;
  __int16 field_1FA;
  __int16 field_1FC;
  __int16 field_1FE;
  __int16 field_200;
  __int16 field_202;
  __int16 field_204;
  __int16 field_206;
  __int16 field_208;
  __int16 field_20A;
  __int16 field_20C;
  __int16 field_20E;
  __int16 field_210;
  __int16 field_212;
  __int16 field_214;
  __int16 field_216;
  __int16 field_218;
  __int16 field_21A;
  __int16 field_21C;
  __int16 field_21E;
  __int16 field_220;
  __int16 field_222;
  __int16 field_224;
  __int16 field_226;
  __int16 field_228;
  __int16 field_22A;
  __int16 field_22C;
  __int16 field_22E;
  __int16 field_230;
  __int16 field_232;
  __int16 field_234;
  __int16 field_236;
  __int16 field_238;
  __int16 field_23A;
  __int16 field_23C;
  __int16 field_23E;
  __int16 field_240;
  __int16 field_242;
  __int16 field_244;
  __int16 field_246;
  __int16 field_248;
  __int16 field_24A;
  __int16 field_24C;
  __int16 field_24E;
  __int16 field_250;
  __int16 field_252;
  __int16 field_254;
  __int16 field_256;
  __int16 field_258;
  __int16 field_25A;
  __int16 field_25C;
  __int16 field_25E;
  __int16 field_260;
  __int16 field_262;
  __int16 field_264;
  __int16 field_266;
  __int16 field_268;
  __int16 field_26A;
  __int16 field_26C;
  __int16 field_26E;
  __int16 field_270;
  __int16 field_272;
  __int16 field_274;
  __int16 field_276;
  __int16 field_278;
  __int16 field_27A;
  __int16 field_27C;
  __int16 field_27E;
  __int16 field_280;
  __int16 field_282;
  __int16 field_284;
  __int16 field_286;
  __int16 field_288;
  __int16 field_28A;
  __int16 field_28C;
  __int16 field_28E;
  __int16 field_290;
  __int16 field_292;
  __int16 field_294;
  __int16 field_296;
  __int16 field_298;
  __int16 field_29A;
  __int16 field_29C;
  __int16 field_29E;
  __int16 field_2A0;
  __int16 field_2A2;
  __int16 field_2A4;
  __int16 field_2A6;
  __int16 field_2A8;
  __int16 field_2AA;
  __int16 field_2AC;
  __int16 field_2AE;
  __int16 field_2B0;
  __int16 field_2B2;
  __int16 field_2B4;
  __int16 field_2B6;
  __int16 field_2B8;
  __int16 field_2BA;
  __int16 field_2BC;
  __int16 field_2BE;
  __int16 field_2C0;
  __int16 field_2C2;
  __int16 field_2C4;
  __int16 field_2C6;
  __int16 field_2C8;
  __int16 field_2CA;
  __int16 field_2CC;
  __int16 field_2CE;
  __int16 field_2D0;
  __int16 field_2D2;
};

/* 49 */
enum agent_inventory_enum
{
  Empty = 0x0,
  Megapol_AP_Grenade = 0x1,
  Megapol_Stun_Grenade = 0x2,
  Megapol_Smoke_Grenade = 0x3,
};

/* 50 */
struct agent_inventory_struct;

/* 51 */
struct __attribute__((aligned(2))) unit_dat_struct
{
  __int16 image;
  char ID;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char side;
  char field_1F;
  char AI_control;
  char field_21;
  char field_22;
  char field_23;
  char field_24;
  char rank;
  char field_26;
  char field_27;
  char unk;
  char speed_curr;
  char current_max_speed;
  char stamina_curr;
  char stamina_strt;
  char reaction_cyrr;
  char reaction_start;
  char braverly_curr;
  char psi_energy_curr;
  char psi_energy_strt;
  char psi_attack_start;
  char psi_defece_curr;
  char psi_defece_start;
  char field_35;
  char accuracy_curr;
  char field_37;
  char current_accuracy;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char health_max_curr;
  char field_3F;
  char health_curr;
  char field_41;
  char leg_type;
  char field_43;
  char field_44;
  char field_45;
  __int16 field_46;
  __int16 field_48;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char gender;
  char field_4F;
  char field_50;
  char face_image;
  char field_52;
  char photo_image;
  __int16 field_54;
  __int16 field_56;
  __int16 field_58;
  char field_5A;
  char equip_set_1;
  char equip_set_2;
  char equip_set_3;
  char equip_set_4;
  char equip_set_5;
  char r_arm_armor;
  char field_61;
  __int16 size_x;
  __int16 size_y;
  char unit_type;
  char field_67;
  char movement_type;
  char field_69;
  char inventory;
  char strenght_curr;
  char strenght_start;
  char field_6D;
  char field_6E;
  char damage_modifier_group;
  __int16 day_in_servis;
  __int16 kills;
  __int16 missions;
  char Score_;
  char medals;
  __int16 x_size;
  __int16 y_size;
  __int16 z_size;
  char field_7E;
  char field_7F;
  char field_80;
  char field_81;
  char img;
  char field_83;
  char field_84;
  char field_85;
  char field_86;
  char field_87;
  char speed_3;
  char health_3;
  char stamina_3;
  char reaction_3;
  char strenght_3;
  char braverly_3;
  char accuracy_3;
  char psi_energy_3;
  char psi_attack_3;
  char psi_defece_4;
};

/* 52 */
struct __attribute__((aligned(2))) agent_equipment_1
{
  __int16 score;
  char item_type;
  char item_effect;
  __int16 weight;
  __int16 picture;
  char size_x;
  char size_y;
  __int16 manufacturer;
  char storage_space_needed;
  char armor_rating;
  char unknown_11;
  char unknown_12;
  __int16 unused_13;
};

/* 53 */
struct __attribute__((aligned(2))) agent_equipment_2_0
{
  char unused_1;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 unknown_2;
  char armor_position;
  char armor_rating;
  char damage_modifier_type;
  __int16 unknown_6;
  __int16 unused_7;
};

/* 54 */
struct __attribute__((aligned(2))) agent_equipment_2_1
{
  char primary_ammo_effect;
  char secondary_ammo_effect;
  char tertiary_ammo_effect;
  char max_primary_rounds;
  char max_secondary_rounds;
  char max_tertiary_rounds;
  char primary_recharge_speed;
  char secondary_recharge_speed;
  char tertiary_recharge_speed;
  char unused_9;
  char unused_10;
  char unused_11;
  __int16 ammo_type_used;
  __int16 grenade_effect;
};

/* 55 */
struct __attribute__((aligned(2))) agent_equipment_2_2
{
  char ammo_effect;
  char rounds;
  char recharge_speed;
  char unused_3;
  char unused_4;
  char unused_5;
  __int16 unknown_6;
  __int16 ammo_type;
  char item_type;
  char unused_10;
};

/* 56 */
struct ufo_loudouts
{
  int alien_egg;
  int brainsucker;
  int multiworm;
  int hyperworm;
  int chrysalis;
  int anthropod;
  int skeletoid;
  int spitter;
  int popper;
  int megaspawn;
  int psimorph;
  int queenspawn;
  int micronoid_aggregate;
  int brainsucker_pod;
};

/* 57 */
struct vehicle_save_data;

/* 58 */
struct __attribute__((aligned(2))) agent_equipmen_3
{
  __int16 speed;
  __int16 projectile_image;
  __int16 power;
  __int16 accuracy;
  __int16 fire_delay;
  __int16 unknown_6;
  __int16 guided;
  __int16 tune_rate;
  __int16 range;
  __int16 projectile_lifetime;
  __int16 unknown_11;
  __int16 unknown_12;
  __int16 explosion_graphic;
  __int16 unused14;
  __int16 firing_sound;
  __int16 impact_sound;
  __int16 demage_type;
  __int16 proximity_trigger_type;
  __int16 depletion_rate;
};

/* 59 */
enum item_1_type
{
  protect = 0x0,
  weapon = 0x1,
  other = 0x2,
  none = 0x4,
};

/* 60 */
enum damage_modif_type
{
  marsec_m4000_mg = 6,
  marsec_armor = 18,
};

/* 61 */
enum status_unit
{
  no_status = 0x0,
  panic = 0x1,
  panic_2 = 0x2,
  berserk = 0x3,
  frozen = 0x4,
};

/* 62 */
struct __attribute__((aligned(4))) score_req
{
  int level_2;
  int level_3;
  int level_4;
  int level_5;
  int level_6;
  int level_7;
  int level_8;
};

/* 63 */
struct __attribute__((aligned(4))) LOF_struct
{
  int width;
  int height;
  int length_masks;
};

/* 64 */
struct __attribute__((aligned(4))) brain_dat_struc
{
  int index;
  int item_count;
  int section;
  int full_sec1[926];
  int full_sec2[926];
  int full_sec3[926];
  int full_sec4[926];
  int full_sec5[926];
  int full_sec16[926];
};

/* 65 */
struct __attribute__((aligned(4))) score_structure
{
  int combat_rating;
  int casual_penalty;
  int leadership_bonus;
  int live_alien_capture;
  int equip_capture;
  int equip_lost;
  int total_score;
  int mission_performans;
};

/* 66 */
struct __attribute__((packed)) __attribute__((aligned(2))) expirean_struc
{
  __int16 flag;
  int index;
  int max_value;
  int entry[25];
  int section;
};

/* 67 */
enum unit_side
{
  alien = 1,
  civilian = 27,
};

/* 68 */
enum Agressive_setting
{
  safe = 0x0,
  coutious = 0x1,
  Agresive = 0x2,
};

/* 69 */
enum fire_mode
{
  no_shot = 0x0,
  auto_shot = 0x1,
  snap_shot = 0x2,
  aimed_shot = 0x3,
};

/* 70 */
enum unit_image
{
  xcom = 0x0,
  egg = 0x1,
  brainsucer = 0x2,
  multiworm = 0x3,
  hyperworm = 0x4,
  chrysalis = 0x5,
  anthropod = 0x6,
  skeletoid = 0x7,
  spitter = 0x8,
  popper = 0x9,
  megaspawn = 0xA,
  psimorph = 0xB,
  queenspawn = 0xC,
  corporate_boss = 0x15,
  not_use = 0xFFFFFFFF,
};

/* 71 */
enum game_type
{
  real_time_game = 0x1,
  TB_game = 0x2,
  net_game_ = 0x3,
};

/* 72 */
struct __attribute__((aligned(4))) experian_array_9
{
  int unit_count;
  int brainsucer_num;
  int avr_max_health;
  int avr_current_health;
  int avr_curr_TU;
  int avr_number_of_units_hit;
  int avr_damage_taken;
  int coord_dispersion;
  int avr_losarea_value;
};

/* 73 */
enum unit_equipment_1
{
  Heavy_launcher_HE_missile = 0x9,
};

/* 74 */
enum unit_equipment_2_2
{
  personal_disruptor_shield = 0x8,
  personal_teleporter = 0x9,
};

/* 75 */
struct __attribute__((aligned(2))) los_area_struc
{
  char field_0;
  char field_1;
  __int16 x_coord1;
  __int16 y_coord1;
  __int16 z_coord1;
  __int16 x_coord2;
  __int16 y_coord2;
  __int16 z_coord2;
  __int16 sections_x;
  __int16 sections_y;
  __int16 sections_z;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  char field_22;
  char field_23;
  char field_24;
  char field_25;
  char field_26;
  char field_27;
  char field_28;
  char field_29;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char field_30;
  char field_31;
  char field_32;
  char field_33;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char field_3E;
  char field_3F;
  char field_40;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char field_4E;
  char field_4F;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  char field_5A;
  char field_5B;
  char field_5C;
  char field_5D;
  char field_5E;
  char field_5F;
  char field_60;
  char field_61;
  char org_offset[28];
  char field_7E;
  char field_7F;
  char field_80;
  char field_81;
  char AI_Patrol_Priority;
  char AI_Target_Priority;
  char Spawn_Type;
  char Spawn_Priority;
  char Can_Deploy_Large_Units;
  char Can_Deploy_Non_Flying_Units;
};

/* 76 */
struct __attribute__((aligned(4))) sections_dat_struc
{
  int x1;
  int y1;
  int z1;
  int x2;
  int y2;
  int z2;
};

/* 77 */
struct __attribute__((aligned(4))) unit_equipset_builtin
{
  int weapon_type1;
  int appearance_chance;
  int clip_type;
  int clip_amount;
  int weapon_type2;
  int appearance_weap2;
  int clip_type2;
  int clip_amount2;
  int equipment_type1;
  int appearance_eq1;
  int equip1_emount;
  int equipment_type2;
  int appearance_eq2;
  int equip2_emount;
  int equipment_type3;
  int appearance_eq3;
  int equip3_emount;
  int equipment_type4;
  int appearance_eq4;
  int equip4_emount;
  int equipment_type5;
  int appearance_eq5;
  int equip5_emount;
};

/* 78 */
struct __attribute__((aligned(4))) experian_array_17
{
  int number;
  int brainsucer_num;
  int average_max_health;
  int average_current_health;
  int average_curr_max_TU;
  int number_of_units_hit;
  int avr_damage_taken;
  int average_dist;
  int WEAPEXP_2_value;
  int number_2;
  int lose_health;
  int field_2C;
  int dist;
  int WEAPEXP_1_value;
  int constant;
  int field_39;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
};

/* 79 */
struct __attribute__((aligned(4))) experian_array_12
{
  int number;
  int brainsucer_num;
  int average_max_health;
  int average_current_health;
  int average_curr_max_TU;
  int number_of_units_hit;
  int avr_damage_taken;
  int average_dist;
  int losarea_field_62;
  int fuild_62_value;
  int losarea_val_9ED80_1;
  int losarea_val_9ED80_2;
  int field_30;
  int field_37;
  int field_38;
  int field_39;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
};

/* 80 */
struct __attribute__((aligned(4))) experian_array_16
{
  int number;
  int brainsucer_num;
  int average_max_health;
  int average_current_health;
  int average_curr_max_TU;
  int number_of_units_hit;
  int avr_damage_taken;
  int average_dist;
  int WEAPEXP_2_value;
  int num_2;
  int max_health_array;
  int agent_move_mode;
  int dist;
  int WEAPEXP_1_value;
  int constant;
  int field_39;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
};

/* 81 */
struct __attribute__((aligned(4))) experian_array_9_11
{
  int squad_count;
  int brainsucer_num;
  int average_max_health;
  int average_current_health;
  int number_of_units_hit;
  int avr_damage_taken;
  int losarea1;
  int average_dist;
  int losarea2;
  int field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_32;
  int field_38;
  int field_39;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
};

/* 82 */
struct __attribute__((aligned(2))) behavior_struc
{
  char beh_0;
  char beh_2;
  char item_group;
  char item_type;
  char unit_action;
  char agent_beh;
  char ammo_power;
  char AI_control_none;
  __int16 x_pos;
  __int16 y_pos;
  __int16 z_pos;
  __int16 beh_ai_control;
  __int16 mode;
  __int16 game_speed;
  __int16 armor_rating;
};

/* 83 */
struct veh_equip_32
{
  __int16 prog_speed;
  __int16 prog_image;
  __int16 damage;
  __int16 accuracy;
  __int16 fire_delay;
  __int16 tail_size;
  __int16 guided;
  __int16 turn_rate;
  __int16 range;
  __int16 projectile_lifetime;
  __int16 horizontal_firing_arc;
  __int16 vertical_firing_arc;
  __int16 point_defence;
  __int16 splits_in_projectile;
  __int16 firing_sound;
  __int16 impact_sound;
  __int16 explosion_graphic;
};

/* 84 */
struct __attribute__((packed)) __attribute__((aligned(1))) unit_equip_set
{
  __int16 weapon_1;
  __int16 clip_type_1;
  __int16 clip_amount_1;
  __int16 weapon_2;
  __int16 clip_type_2;
  __int16 clip_amount_2;
  __int16 weapon_3;
  __int16 clip_type_3;
  __int16 clip_amount_3;
  __int16 weapon_4;
  __int16 clip_type_4;
  __int16 clip_amount_4;
  __int16 weapon_5;
  __int16 clip_type_5;
  __int16 clip_amount_5;
  __int16 weapon_6;
  __int16 clip_type_6;
  __int16 clip_amount_6;
  _BYTE gap24[1];
  __int16 clip_type_7;
  __int16 clip_amount_7;
  __int16 weapon_8;
  __int16 clip_type_8;
  __int16 clip_amount_8;
  __int16 weapon_9;
  __int16 clip_type_9;
  __int16 clip_amount_9;
  __int16 weapon_10;
  __int16 clip_type_10;
  __int16 clip_amount_10;
  __int16 grenade_type_1;
  __int16 grenade_amount_1;
  __int16 grenade_type_2;
  __int16 grenade_amount_2;
  __int16 grenade_type_3;
  __int16 grenade_amount_3;
  __int16 grenade_type_4;
  __int16 grenade_amount_4;
  __int16 grenade_type_5;
  __int16 grenade_amount_5;
  __int16 grenade_type_6;
  __int16 grenade_amount_6;
  __int16 grenade_type_7;
  __int16 grenade_amount_7;
  __int16 grenade_type_8;
  __int16 grenade_amount_8;
  __int16 grenade_type_9;
  __int16 grenade_amount_9;
  __int16 grenade_type_10;
  __int16 grenade_amount_10;
  __int16 other_equip1;
  __int16 other_equip2;
  __int16 other_equip3;
  __int16 other_equip4;
  __int16 other_equip5;
  __int16 other_equip6;
  __int16 other_equip7;
  __int16 other_equip8;
  __int16 other_equip9;
  __int16 other_equip10;
  __int16 other_equip11;
  __int16 other_equip12;
  __int16 other_equip13;
  __int16 other_equip14;
  __int16 other_equip15;
  __int16 other_equip16;
  __int16 other_equip17;
  __int16 other_equip18;
  __int16 other_equip19;
  __int16 other_equip20;
};

/* 85 */
struct __attribute__((aligned(2))) object_dat_struc
{
  char owned_org;
  char score;
  char equipment;
  char unit_num;
  char x_pos;
  char y_pos;
  char z_pos;
  char brainsucker_status;
  char lof;
  char power;
  __int16 max_primary_rounds;
  char ammo_type;
  char field_D;
  __int16 armor_rating;
  __int16 move_struc;
  char orgs_array[28];
  char orgs_array_beh;
  char field_2F;
};

/* 86 */
enum equip_3_damage_type
{
  incendiary = 0x2,
  stun = 0x5,
};

/* 87 */
enum gender
{
  male = 0x0,
  female = 0x1,
  android = 0x2,
};

/* 88 */
enum weapon_type
{
  entropy_launcher = 27,
};

/* 89 */
enum Explosion_Type
{
  smoke = 0x0,
  alien_gas = 0x1,
  fire = 0x2,
  Stun_Gas = 0x3,
  High_Explosive = 0x4,
  Stun = 0x5,
  Psionic_Blast = 0x6,
};

/* 90 */
enum map_tile_side
{
  grounmap = 0x0,
  leftmap = 0x1,
  rightmap = 0x2,
  featmap = 0x3,
  featmap_4 = 0x4,
};

/* 91 */
enum area_spawn_type
{
  X_Com = 0x0,
  Rival_Organisations = 0x1,
  Civilians = 0x2,
  Civilians_3 = 0x3,
};

/* 92 */
struct __attribute__((aligned(2))) ptang_struc
{
  __int16 pic_num;
  __int16 x_pos_3d;
  __int16 y_pos_3D;
  __int16 z_pos_3d;
  __int16 fuild_8;
};

/* 93 */
struct __attribute__((aligned(2))) struc_23
{
  __int16 fuild_1;
  __int16 x;
  __int16 y;
  __int16 z;
  __int16 fuild_6;
  __int16 field_A;
  __int16 field_C;
  __int16 field_E;
  __int16 field_10;
};

/* 94 */
struct __attribute__((packed)) __attribute__((aligned(2))) save_struct
{
  int length;
  void *offset;
  __int16 field_8;
};

/* 95 */
enum equipment_1
{
  megapol_plasma_gun = 16,
  megapol_plasma_pod = 17,
  forceweb = 32,
  disruptor_gun = 41,
  disruptor_2A = 42,
};

/* 96 */
enum hand
{
  r_hand = 0x0,
  l_hand = 0x1,
  right_leg = 0x2,
  right_3 = 0x3,
};

/* 97 */
struct __attribute__((aligned(2))) text_string_41
{
  char field_0[41];
};

/* 98 */
struct __attribute__((aligned(2))) weapon_effect_size
{
  __int16 x_size;
  __int16 y_size;
  __int16 z_size;
};

/* 99 */
struct __attribute__((aligned(4))) psio_control_unit_struct
{
  __int16 obj_dat_sec;
  __int16 field_2;
  int unit_1;
  int unit_2;
  __int16 AI_control;
  __int16 side;
  __int16 field_10;
  __int16 field_12;
};

/* 100 */
enum move_mode
{
  crawl = 0x0,
  walk = 0x1,
  run = 0x2,
};

/* 101 */
struct __attribute__((aligned(2))) move_unit_struc
{
  __int16 direction;
  __int16 unit;
  __int16 x_pos_3D;
  __int16 y_pos_3D;
  __int16 z_pos_3D;
  __int16 x_pos_delta;
  __int16 y_pos_delta;
  __int16 field_E;
  __int16 game_speed;
  __int16 x_pos_3D_2;
  __int16 y_pos_3D_2;
  __int16 z_pos_3D_2;
  __int16 unit_2;
  char side;
  char field_1B;
  __int16 field_1C;
};

/* 102 */
enum direction
{
  direction_x = 0x1,
  direction_y = 0x2,
  direction_x_y = 0x4,
};

/* 103 */
struct __attribute__((aligned(4))) experian_array_25
{
  int unit_count;
  int brainsucer_num;
  int average_max_health;
  int average_current_health;
  int average_curr_max_TU;
  int number_of_units_hit;
  int damage_taken_counter;
  int coord_dispersion;
  int avr_losarea_value;
  int number_of_units_hit_3;
  int WEAPEXP_2;
  int accuracy;
  int agent_count;
  int max_health;
  int current_health;
  int curr_max_TU;
  int number_of_units_hit_2;
  int dispersion_2;
  int protect;
  int squad_count;
  int aver_max_health;
  int avr_move_mode;
  int dispersion;
  int WEAPEXP_1;
  int dist;
};

/* 104 */
struct __attribute__((aligned(4))) brain_main
{
  int array_1[12];
  int array_1_total;
  int array_2[25];
};

/* 105 */
struct __attribute__((aligned(4))) scenario_dat
{
  char map_name[40];
  int total_tac_map_x_size;
  int total_tac_map_y_size;
  int total_tac_map_z_size;
  int scenario_type;
  int xcom_mission_type;
  int year_tac;
  int month_tac;
  int week__tac;
  int day_tac;
  int hour_tac;
  int minute_tac;
  int second_tac;
  int bldn_num;
  int bld_function_sc;
  int bld_owner_sc;
  int bld_relation;
  int field_6A;
  int field_6C;
  int field_70;
  int field_74;
  int bld_ship_type_mission;
  char rank_sum[7];
  int field_84;
  int field_88;
  int field_8C;
  int field_90;
  int field_94;
  int field_98;
  int field_9C;
  int field_A0;
  int field_A4;
  int field_A8;
  int diff_enum;
  int field_B0;
  int MISSION_BRIEFING_header;
  int tac_score;
  int field_BC;
  char field_C0;
  char field_C1;
  char field_C2;
  char field_C3;
  int field_C4;
  int field_C8;
  int field_CC;
  int field_D0;
};

/* 106 */
enum item_2_2_type
{
  ammo_clip = 0x0,
  motion_scanner = 0x1,
  Probe = 0x2,
  vortex_analizer = 0x3,
  multitracker = 0x4,
  mind_shild = 0x5,
  mind_bender = 0x6,
  alien_detector = 0x7,
  pers_disr_shield = 0x8,
  pers_teleporter = 0x9,
  pers_cloacking_field = 0xA,
  dim_force_field = 0xB,
  medikit = 0xC,
};

/* 107 */
enum xcom_mission_type
{
  common_mission = 0x1,
  Marsec_mission = 0x2,
  Alien_mission = 0x3,
  megapol_mission = 0x4,
};

/* 108 */
enum behavior_action
{
  displacement = 1,
  behavior_action_2 = 2,
  move_mode_ch = 3,
  Aggressive_mode_ch = 4,
  set_waypoint = 5,
  fire_to_unit = 6,
  change_hand_weapon = 7,
  behavior_action_8 = 8,
  change_direction = 9,
  check_alied_unit_ = 10,
  behavior_action_B = 11,
  fire_to_map = 12,
  Stand_kneel = 13,
  g_speed_sync = 14,
  unit_SYNC_error = 15,
  add_in_squad = 16,
  choice_item_in_hand = 17,
  increse_game_counter = 18,
  prime_grenad = 19,
  throw = 20,
  freed_from_Psionic_control = 21,
  fire_mod_ch = 22,
  teleports = 23,
  move_to_point = 24,
  behavior_action_19 = 25,
  unkn_format_action = 26,
  behavior_action_1B = 27,
  behavior_action_1C = 28,
  behavior_action_1D = 29,
  set_exp_array_num = 30,
  behavior_action_1F = 31,
  Drop_R_hand = 32,
  Drop_L_hand = 33,
  behavior_action_22 = 34,
  Reserve_TU_shot = 35,
  Reserve_TU_kneel = 36,
  group_format_action = 37,
  single_file_action = 38,
  use_medikit = 39,
  check_freed_from_Psionic_control = 40,
  unit_died = 41,
};

/* 109 */
struct object_dat
{
};

/* 110 */
struct __attribute__((packed)) __attribute__((aligned(2))) struc_agent
{
  __int16 image;
  __int16 image_2;
  __int16 ID;
  char name[26];
  __int16 side;
  __int16 unit_type;
  __int16 AI_control;
  __int16 squad;
  __int16 anim_offset;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char rank;
  __int16 field_30;
  __int16 r_hend_weapon;
  __int16 l_hand_weapon;
  __int16 weapon_weight;
  __int16 total_encumberan;
  __int16 Days_service;
  __int16 Kills;
  __int16 missions;
  __int16 score;
  __int16 total_kill_score;
  char calc_score;
  char leg_typs;
  __int16 legs_armor;
  __int16 body_armor;
  __int16 l_arm_armor;
  __int16 r_arm_armor;
  __int16 head_armor;
  __int16 uncnown_armor;
  char leg_wound;
  char tors_wound;
  char l_hend_wound;
  char r_hend_wound;
  char head_wound;
  char rear_wound;
  char max_speed;
  char max_TU;
  char curr_speed;
  char field_5B;
  __int16 Reserve_TU_shot;
  __int16 Reserve_TU_kneel;
  char cloak_dist;
  char field_61;
  __int16 max_health;
  __int16 current_health;
  char morale_1;
  char morale_2;
  char stamina_1;
  char stamina_2;
  char stamina_usage_count;
  char field_6B;
  char curent_reaction;
  char max_reaction;
  char auto_shot_counter;
  char field_6F;
  char strenght_1;
  char strenght_2;
  char curr_morale;
  char braverly;
  char psi_energy_1;
  char psi_energy_2;
  char field_76;
  char field_77;
  char field_78;
  char field_79;
  char field_7A;
  char field_7B;
  char unit_status;
  char agressive_mode_2;
  char fire_mode_2;
  char field_7F;
  __int16 stun_level;
  char fire_damage;
  char field_83;
  __int16 attack_unit_num;
  __int16 field_86;
  char psi_defece_curr;
  char psi_defece_1;
  char psi_defece_2;
  char field_8B;
  __int16 accuracy;
  __int16 current_accuracy;
  char field_90;
  char field_91;
  char field_92;
  char field_93;
  char field_94;
  char field_95;
  char gender;
  char face_image;
  char field_98;
  char field_99;
  char photo_image;
  char field_9B;
  char field_9C;
  char field_9D;
  char field_9E;
  char field_9F;
  char field_A0;
  char field_A1;
  char equip_set_1;
  char equip_set_2;
  char equip_set_3;
  char equip_set_4;
  char equip_set_5;
  char field_A7;
  __int16 tracker_state;
  __int16 x_pos;
  __int16 y_pos;
  __int16 z_pos;
  char field_B0;
  char field_B1;
  char field_B2;
  char field_B3;
  char field_B4;
  char field_B5;
  char field_B6;
  char field_B7;
  char field_B8;
  char field_B9;
  __int16 x_pos_3D;
  __int16 y_pos_3D;
  __int16 z_pos_3D;
  __int16 x_size;
  __int16 y_size;
  __int16 z_size;
  char field_C6;
  char field_C7;
  char field_C8;
  char field_C9;
  char field_CA;
  char field_CB;
  char field_CC;
  char field_CD;
  __int16 lof_height;
  __int16 size_x_1;
  __int16 x_pos_move_target;
  __int16 y_pos_move_target;
  __int16 z_pos_move_target;
  __int16 x_pos_1;
  __int16 y_pos_1;
  __int16 z_pos_1;
  char Object_height;
  char field_DF;
  char x_pos_2;
  char y_pos_2;
  char z_pos_2;
  char field_E3;
  char field_E4;
  char field_E5;
  char field_E6;
  char field_E7;
  char field_E8;
  char field_E9;
  char field_EA;
  char field_EB;
  char field_EC;
  char field_ED;
  char direct_2d;
  char item_size_y;
  char item_size_z;
  char field_F1;
  __int16 direct_3d;
  __int16 field_F4;
  __int16 field_F6;
  __int16 move_mode;
  __int16 field_FA;
  __int16 field_FC;
  char max_speed_2_mod;
  char field_FF;
  __int16 curr_TU;
  __int16 current_frame_speed_by_moving_mode;
  char field_104;
  char field_105;
  char field_106;
  char field_107;
  __int16 lof_offset;
  char x_pos_3;
  char y_pos_3;
  char z_pos_3;
  char field_10D;
  __int16 z_pos_6;
  __int16 turet_size_2;
  __int16 field_112;
  __int16 field_114;
  __int16 field_116;
  __int16 field_118;
  __int16 field_11A;
  __int16 field_11C;
  __int16 field_11E;
  __int16 field_120;
  __int16 field_122;
  __int16 field_124;
  __int16 field_126;
  __int16 field_128;
  __int16 field_12A;
  __int16 field_12C;
  __int16 field_12E;
  __int16 field_130;
  __int16 field_132;
  __int16 field_134;
  __int16 field_136;
  __int16 field_138;
  __int16 field_13A;
  __int16 field_13C;
  __int16 field_13E;
  __int16 field_140;
  __int16 field_142;
  __int16 field_144;
  __int16 field_146;
  __int16 field_148;
  __int16 field_14A;
  __int16 field_14C;
  __int16 field_14E;
  __int16 field_150;
  __int16 field_152;
  __int16 field_154;
  __int16 field_156;
  __int16 field_158;
  __int16 field_15A;
  __int16 field_15C;
  __int16 field_15E;
  __int16 field_160;
  __int16 field_162;
  __int16 field_164;
  __int16 field_166;
  __int16 field_168;
  __int16 field_16A;
  __int16 field_16C;
  __int16 field_16E;
  __int16 field_170;
  __int16 field_172;
  __int16 field_174;
  __int16 field_176;
  __int16 field_178;
  __int16 field_17A;
  __int16 field_17C;
  __int16 field_17E;
  __int16 field_180;
  __int16 field_182;
  __int16 field_184;
  __int16 field_186;
  __int16 field_188;
  __int16 field_18A;
  __int16 field_18C;
  __int16 field_18E;
  __int16 field_190;
  __int16 field_192;
  __int16 field_194;
  __int16 field_196;
  __int16 field_198;
  __int16 field_19A;
  __int16 field_19C;
  __int16 field_19E;
  __int16 field_1A0;
  __int16 field_1A2;
  __int16 field_1A4;
  __int16 field_1A6;
  __int16 field_1A8;
  __int16 field_1AA;
  __int16 field_1AC;
  __int16 field_1AE;
  __int16 field_1B0;
  __int16 field_1B2;
  __int16 field_1B4;
  __int16 field_1B6;
  __int16 field_1B8;
  __int16 field_1BA;
  __int16 field_1BC;
  __int16 field_1BE;
  __int16 field_1C0;
  __int16 field_1C2;
  __int16 field_1C4;
  __int16 field_1C6;
  __int16 field_1C8;
  __int16 field_1CA;
  __int16 field_1CC;
  __int16 field_1CE;
  __int16 field_1D0;
  __int16 field_1D2;
  char losarea_sec_num;
  char field_1D5;
  char losar_sec_num[10];
  char field_1E0;
  char field_1E1;
  char field_1E2;
  char field_1E3;
  char field_1E4;
  char field_1E5;
  char field_1E6;
  char field_1E7;
  char field_1E8;
  char field_1E9;
  char field_1EA;
  char field_1EB;
  char field_1EC;
  char field_1ED;
  char field_1EE;
  char field_1EF;
  char field_1F0;
  char field_1F1;
  char field_1F2;
  char field_1F3;
  char field_1F4;
  char field_1F5;
  char field_1F6;
  char field_1F7;
  char field_1F8;
  char field_1F9;
  char field_1FA;
  char field_1FB;
  char field_1FC;
  char field_1FD;
  char field_1FE;
  char field_1FF;
  char field_200;
  char field_201;
  char field_202;
  char field_203;
  char field_204;
  char field_205;
  char field_206;
  char field_207;
  char field_208;
  char field_209;
  char field_20A;
  char field_20B;
  char field_20C;
  char field_20D;
  char field_20E;
  char field_20F;
  char field_210;
  char field_211;
  char field_212;
  char field_213;
  __int16 x_pos_4;
  __int16 y_pos_4;
  __int16 z_pos_4;
  __int16 agent_in_aim;
  __int16 kneeling;
  __int16 movement_mode;
  __int16 agent_formation;
  __int16 agressive_mode;
  __int16 movement_graphic_mode;
  __int16 fire_mode;
  __int16 kneeling_graf_fire;
  __int16 stand_Kneel;
  __int16 kneeling_setting;
  char field_22E;
  char field_22F;
  char field_230;
  char field_231;
  char field_232;
  char field_233;
  char field_234;
  char field_235;
  char field_236;
  char field_237;
  char field_238;
  char field_239;
  char field_23A;
  char field_23B;
  char field_23C;
  char field_23D;
  char field_23E;
  char field_23F;
  char field_240;
  char field_241;
  char field_242;
  char field_243;
  char field_244;
  char field_245;
  char field_246;
  char field_247;
  char field_248;
  char field_249;
  char field_24A;
  char field_24B;
  char field_24C;
  char field_24D;
  char field_24E;
  char field_24F;
  char field_250;
  char field_251;
  char field_252;
  char field_253;
  __int16 sheild_point;
  char field_256;
  char field_257;
  char matrix_action_2_mode;
  char field_259;
  char field_25A;
  char field_25B;
  __int16 proj_owner_unit_num;
  char num_aiming_unit_array[28];
  char field_27A[6];
  char field_280[6];
  char number_of_units_hit;
  char damage_taken_counter;
  char unit_hit_struc;
  char num_aim_unit;
  char field_28A;
  char field_28B;
  char max_health_div_4;
  char field_28D;
  char matrix_action_6_mode;
  char field_28F;
  char unit_alied_num;
  char field_291;
  char field_292;
  char field_293;
  char field_294;
  char field_295;
  char field_296;
  char field_297;
  char field_298;
  char field_299;
  char field_29A;
  char field_29B;
  char field_29C;
  char field_29D;
  char field_29E;
  char field_29F;
  char field_2A0;
  char field_2A1;
  char field_2A2;
  char field_2A3;
  char field_2A4;
  char field_2A5;
  char field_2A6;
  char field_2A7;
  char field_2A8;
  char field_2A9;
  char field_2AA;
  char field_2AB;
  char field_2AC;
  char field_2AD;
  char field_2AE;
  char field_2AF;
  __int16 obj_r_hand;
  __int16 field_2B2;
  __int16 obj_l_hand;
  __int16 field_2B6;
  char inventory;
  char field_2B9;
  char field_2BA;
  char damage_modif_group;
  char movement_type;
  char fly_mod;
  char field_2BE;
  char field_2BF;
  char losection_num;
  char field_2C1;
  int time_array[28];
  __int16 losection_array[28];
  char agent_move_type[28];
  __int16 agent_move_mode[28];
  char r_hand_ammo[28];
  char l_hand_ammo[28];
  char lose_health_arr[28];
  char squad_unk;
  char field_413;
  char field_414;
  char field_415;
  char field_416;
  char field_417;
  char field_418;
  char field_419;
  __int16 matrix_ai_control_xcom;
  __int16 matrix_ai_control_alien;
  char field_41E;
  char brainsuck_flag;
  char field_420;
  char field_421;
  char field_422;
  char field_423;
  char field_424;
  char field_425;
  char field_426;
  char field_427;
  char field_428;
  char random_matrix_flag;
  char field_42A;
  char field_42B;
  char field_42C;
  char field_42D;
  char time_unc;
  char field_42F;
  char field_430;
  char field_431;
  __int16 exp_array_section;
  __int16 exp_sec_num_2;
  __int16 action_30_array[20];
  __int16 x_pos_unc;
  __int16 y_pos_unc;
  __int16 z_pos_unc;
  char aggr_set_ctrl_unit;
  char movement_graphic_mode_old;
  char fire_mod_old;
  char field_467;
  char field_468;
  char field_469;
  char field_46A;
  char field_46B;
  char matrix_action_27_mode;
  char field_46D;
  char field_46E;
  char field_46F;
  char field_470;
  char field_471;
  char field_472;
  char field_473;
  char field_474;
  char field_475;
  char field_476;
  char matrix_action_28_mode;
  char field_478;
  char unit_weapon_mode;
  char anim_speed;
  char field_47B;
  char field_47C;
  char field_47D;
  char field_47E;
  char field_47F;
  char field_480;
  char field_481;
  char field_482;
  char field_483;
  char field_484;
  char field_485;
  char field_486;
  char field_487;
  __int16 speed_3;
  __int16 health_3;
  __int16 stamina_3;
  __int16 reaction_3;
  __int16 strenght_3;
  __int16 braverly_3;
  __int16 accuracy_3;
  __int16 psi_energy_3;
  __int16 psi_attack_3;
};

/* 111 */
enum alien_bld_func
{
  incubator = 0,
  spawn = 1,
  food = 2,
  megapod = 3,
  sleep = 4,
  organic_factory = 5,
  alien_farm = 6,
  control = 7,
  maintan = 8,
  gate_generator = 9,
};

/* 112 */
struct struc_string_41
{
  char field_0[41];
};

/* 113 */
enum game_mode_enum
{
  real_time = 0,
  turn_game = 1,
};

/* 114 */
enum reserv_TU_shot
{
  reserv_TU_Auto = 1,
  reserv_TU_Snap = 2,
  reserv_TU_Aim = 3,
  None = 18446744073709551615,
};

/* 115 */
struct tile_struc_unused
{
  __int16 coord_x;
  __int16 coord_y;
  __int16 coord_z;
};

/* 116 */
enum kneeling
{
  stend_up = 0,
  kneel_down = 1,
};

/* 117 */
enum test_enum
{
  description = 0,
  organisation = 1,
  squad = 2,
  player = 3,
  createunit = 4,
  equip1 = 5,
  equip2 = 6,
  equipbody = 7,
  armour = 8,
  type = 9,
  hiddenterrain = 10,
  trainingdemo = 11,
  x = 12,
  y = 13,
  z = 14,
  autosave = 15,
  aitakeover = 16,
  turnbasedgame = 17,
};

/* 118 */
struct brain_dat_section
{
  int short_min;
  int short_delta;
  int short_value[298];
  int total;
  int long_section[625];
};

