/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'UFO2P4_for_ASM'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
enum font
{
  smalfont = 0x0,
  smallset = 0x1,
  bigfont = 0x2,
};

/* 2 */
enum agent_inventory_enum
{
  Empty = 0x0,
  Megapol_AP_Grenade = 0x1,
  Megapol_Stun_Grenade = 0x2,
  Megapol_Smoke_Grenade = 0x3,
};

/* 3 */
enum alert_gruop
{
  alert_Group = 0x0,
  alert_1 = 0x1,
  alert_2 = 0x2,
  alert_3 = 0x3,
};

/* 4 */
enum direct_damage
{
  rear = 0x0,
  top = 0x1,
  right = 0x2,
  left = 0x3,
  under = 0x4,
  front = 0x5,
};

/* 5 */
enum rules_of_engagement
{
  Evasive = 0x0,
  Defensive = 0x1,
  Standard = 0x2,
  Aggressive = 0x3,
  unkn_4 = 0x4,
  attack_building = 0x5,
  police = 0x6,
  alien_drop = 0x7,
  micronoid_rain = 0x8,
  unkn_9 = 0x9,
  overspawn_drop = 0xA,
  escort = 0xB,
};

/* 6 */
enum craft_type
{
  craft_type_2 = 0x2,
  space_liner = 0xF,
  police_car = 0x1B,
  ovwespawn = 0x21,
};

/* 7 */
enum agent_assignment_type
{
  building = 0x1,
  tube = 0x2,
  vehicle_ = 0x3,
  inactive = 0xFFFFFFFF,
};

/* 8 */
enum org_enum
{
  X_COM = 0x0,
  Alien = 0x1,
  Government = 0x2,
  Megapol = 0x3,
  Cult_of_Sirius = 0x4,
  Marsec = 0x5,
  Superdynamics = 0x6,
  General_Metro = 0x7,
  Cyberweb = 0x8,
  Transtellar = 0x9,
  Solmine = 0xA,
  Sensovision = 0xB,
  Lifetree = 0xC,
  Nutrivend = 0xD,
  Evonet = 0xE,
  Sanctuary_Clinic = 0xF,
  Nanotech = 0x10,
  Energen = 0x11,
  Synthemesh = 0x12,
  Gravball_League = 0x13,
  Psyke = 0x14,
  Diablo = 0x15,
  Osiron = 0x16,
  SELF = 0x17,
  Mutant_Alliance = 0x18,
  Extropians = 0x19,
  Technocrats = 0x1A,
  Civilian = 0x1B,
};

/* 9 */
enum bld_funcion
{
  Space_Port = 0x8,
  slums = 0x1C,
  warehouse = 0x1E,
};

/* 10 */
enum movement_type
{
  road = 0x0,
  flying = 0x1,
  overspawn = 0x2,
  not_active = 0xFFFFFFFF,
};

/* 11 */
enum vehicle_mission_type
{
  None = 0x0,
  attack_near_portal_bld = 0x1,
  rain_mission = 0x2,
  drop_missiom = 0x3,
  random_bld_attack = 0x4,
  OVERSP_mission = 0x5,
};

/* 12 */
enum veh_item_type
{
  engine = 0x0,
  weapon = 0x1,
  cargo = 0x2,
  none = 0x4,
};

/* 13 */
enum weapon_type
{
  Janitor_missiles_launcher = 0xA,
  retrib_missile_laluncher = 0xC,
  statis_bomb_launcher = 0xE,
};

/* 14 */
enum armor_pos
{
  legs = 0x0,
  body = 0x1,
  l_arm = 0x2,
  r_arm = 0x3,
  head = 0x4,
  unknow = 0x5,
};

/* 15 */
enum veh_contol_num_comand
{
  Go_to_building = 0x2,
  Attack_hostile_unit = 0x3,
  Go_to_map_point = 0x4,
  Attack_building = 0x6,
  manual = 0x9,
};

/* 16 */
enum veh_assign : __int64
{
  in_city = 0xFFFFFFFFFFFFFFFF,
};

/* 17 */
enum tile_type
{
  general = 0x0,
  roads = 0x1,
  ppl_tube_junc = 0x2,
  ppl_tube = 0x3,
  city_wall = 0x4,
};

/* 18 */
enum road_level_direct
{
  N = 0x0,
  E = 0x1,
  S = 0x2,
  W = 0x3,
  NE = 0x4,
  SE = 0x5,
  SW = 0x6,
  NW = 0x7,
  vertical = 0x8,
};

/* 19 */
enum vertical_direction : __int64
{
  UP = 0x1,
  DOWN = 0xFFFFFFFFFFFFFFFF,
};

/* 20 */
enum agent_hired
{
  not_hired_ = 0x0,
  hired_ = 0x2,
};

/* 21 */
enum facilities
{
  secur_station = 0x17,
  adv_secur_station = 0x18,
  vehicle_repair_bay = 0x19,
  biochenistry_lab = 0x1A,
  adv_biochenistry_lab = 0x1B,
  quantum_phisics_lab = 0x1C,
  adv_quantum_phisics_lab = 0x1D,
  alien_containment = 0x1E,
  adv_alien_containment = 0x1F,
  workshop = 0x20,
  adv_workshop = 0x21,
};

/* 22 */
enum agent_equip_type
{
  protect = 0x0,
  weapons = 0x1,
  other = 0x2,
  no_use = 0x4,
};

/* 23 */
enum road_type
{
  terminal_junction = 0x2,
};

/* 24 */
enum security
{
  megapol_officer = 0xA,
  gangster = 0xB,
  cultist = 0xC,
};

/* 25 */
enum agent_role
{
  xcom_agent = 0x0,
  biochem = 0x1,
  mechan = 0x2,
  physic = 0x3,
};

/* 26 */
enum veh_type
{
  Airtaxi = 0xB,
  Autotaxi = 0x19,
};

/* 27 */
enum facilities_type
{
  medical_bay = 0x14,
  trainning_aria = 0x15,
  psi_gum = 0x16,
};

/* 28 */
enum agent_gender
{
  male = 0x0,
  female = 0x1,
  android = 0x2,
};

/* 29 */
enum start_menu_choise
{
  exit_v = 0x0,
  new_game = 0x1,
  load_game = 0x2,
  scenario = 0x3,
};

/* 30 */
enum vehicle_mission
{
};

/* 31 */
enum ufo_mission_type
{
  attack_buildings = 0x5,
  alien_drops = 0x7,
  mkrn_rain = 0x8,
  owersp_drop = 0xA,
  passive = 0xB,
};

/* 32 */
enum game_speed
{
  slow_sp = 0x1,
  normal_sp = 0x2,
  double_sp = 0x4,
  quadruple_sp = 0x6,
  ultra_sp = 0x3C,
};

/* 33 */
enum unit_type
{
  brainsucker = 0x23,
};

/* 34 */
struct __attribute__((aligned(2))) sob_structure
{
  __int16 x_coord;
  __int16 y_coord;
  __int16 z_coord;
  __int16 priority;
};

/* 35 */
enum agent_equi_1
{
  forceweb = 0x20,
};

/* 36 */
enum xcom_mission_type_
{
  Ivest_mission = 0x1,
  Base_mission = 0x2,
  UFO_mission = 0x3,
  raid = 0x4,
};

/* 37 */
enum SVG_GAME_TYPE
{
  empty = 0x0,
  city_save = 0x1,
  tace_save = 0x2,
};

/* 38 */
enum save_status
{
  option = 0x0,
  load = 0x1,
  delete = 0x2,
};

/* 39 */
enum veh_target_type
{
  build = 0x0,
  veh = 0x1,
  map = 0x2,
  no_targ = 0xFFFFFFFF,
};

/* 40 */
enum Agent_order
{
  no_order = 0x0,
  Return_to_base = 0x1,
  Tailing = 0x4,
  Spying = 0x5,
};

/* 41 */
enum action_raid_enum
{
  Attack = 0x1,
  Raid = 0x2,
  Storm = 0x3,
  notused_1 = 0x4,
  notused_2 = 0x5,
  Illegal_Flayer = 0x6,
  notused_3 = 0x7,
  notused_4 = 0x8,
  Treaty = 0x9,
};

/* 42 */
enum bld_func_dem
{
  bld_ = 0x0,
};

/* 43 */
enum research_flag
{
  The_Alien_Dimension = 0x1,
  Dimension_Probe = 0x2,
  Bio_Transport = 0x3,
  Explorer = 0x4,
  Retaliator = 0x5,
  Annihilator = 0x6,
  Brainsucker_Pods = 0x7,
  Brainsucker_Autopsy = 0x8,
  Brainsucker = 0x9,
  Multiworm_Egg_Autopsy = 0xA,
  Multiworm_Egg = 0xB,
  Multiworm_Autopsy = 0xC,
  Multiworm = 0xD,
  Hyperworm_Autopsy = 0xE,
  Hyperworm = 0xF,
  Chrysalis_Autopsy = 0x10,
  Chrysalis = 0x11,
  Anthropod_Autopsy = 0x12,
  Anthropod = 0x13,
  Psimorph_Autopsy = 0x14,
  Psimorph = 0x15,
  Spitter_Autopsy = 0x16,
  Spitter = 0x17,
  Megaspawn_Autopsy = 0x18,
  Megaspawn = 0x19,
  Popper_Autopsy = 0x1A,
  Popper = 0x1B,
  Skeletoid_Autopsy = 0x1C,
  Skeletoid = 0x1D,
  Micronoid_Autopsy = 0x1E,
  Micronoid = 0x1F,
  Queenspawn_Autopsy = 0x20,
  Queenspawn = 0x21,
  Overspawn_Autopsy = 0x22,
  Overspawn = 0x23,
  The_Alien_Genetic_Structure = 0x24,
  The_Alien_Life_Cycle = 0x25,
  The_Real_Alien_Threat = 0x26,
  Biological_Warfare = 0x27,
  Toxin_Type_B = 0x28,
  Toxin_Type_C = 0x29,
  Alien_Gas = 0x2A,
  Advanced_Security_Station = 0x2B,
  Advanced_Biochemistry_Lab = 0x2C,
  Advanced_Quantum_Physics_Lab = 0x2D,
  Advanced_Alien_Containment = 0x2E,
  Advanced_Workshop = 0x2F,
  Disruptor_Gun = 0x30,
  Devastator_Cannon = 0x31,
  Boomeroid = 0x32,
  Brainsucker_Launcher = 0x33,
  Entropy_Launcher = 0x34,
  Entropy_Pod = 0x35,
  Dimension_Missile_Launcher = 0x36,
  Dimension_Missile = 0x37,
  Vortex_Mine = 0x38,
  Personal_Disruptor_Shield = 0x39,
  Personal_Teleporter = 0x3A,
  Personal_Cloaking_Field = 0x3B,
  Dimension_Destabiliser = 0x3C,
  Disruptor_Armor = 0x3D,
  Light_Disruptor_Beam = 0x3E,
  Medium_Disruptor_Beam = 0x3F,
  Heavy_Disruptor_Beam = 0x40,
  Disruptor_Inversion_Bomb = 0x41,
  Stasis_Field_Bomb = 0x42,
  Disruptor_Multi_Bomb = 0x43,
  X_COM_Advanced_Control_System = 0x44,
  Bio_Transport_Module = 0x45,
  Small_Disruption_Shield = 0x46,
  Large_Disruption_Shield = 0x47,
  Cloaking_Field = 0x48,
  Teleporter = 0x49,
  Dimension_Shifter = 0x4A,
  Alien_Propulsion_System = 0x4B,
  Alien_Control_System = 0x4C,
  Alien_Energy_Source = 0x4D,
  UFO_type_1 = 0x4E,
  UFO_type_2 = 0x4F,
  UFO_type_3 = 0x50,
  UFO_type_4 = 0x51,
  UFO_type_5 = 0x52,
  UFO_type_6 = 0x53,
  UFO_type_7 = 0x54,
  UFO_type_8 = 0x55,
  UFO_type_9 = 0x56,
  UFO_type_10 = 0x57,
  Alien_building1 = 0x58,
  Alien_building2 = 0x59,
  Alien_building3 = 0x5A,
  Alien_building4 = 0x5B,
  Alien_building5 = 0x5C,
  Alien_building6 = 0x5D,
  Alien_building7 = 0x5E,
  Alien_building8 = 0x5F,
  Alien_building9 = 0x60,
  Alien_building10 = 0x61,
  One_way_to_win = 0x62,
};

/* 44 */
#pragma pack(push, 1)
struct struc_1
{
  __int16 field_0;
  __int16 group_number;
  __int16 field_4;
  int track_number;
};
#pragma pack(pop)

/* 45 */
#pragma pack(push, 1)
struct struct_0
{
  __int16 field_0;
  char gap_2[18];
  void *anonymous_1;
  __int16 anonymous_2;
  char gap_1A[3];
  char anonymous_3;
  char field_1E;
  char field_1F;
};
#pragma pack(pop)

/* 46 */
struct __attribute__((aligned(2))) struct_sound
{
  char name[50];
  __attribute__((packed)) __attribute__((aligned(1))) int bitrate;
  __attribute__((packed)) __attribute__((aligned(1))) int ch_size;
  __int16 ch_code;
  __int16 max_vol;
  __int16 field_3E;
};

/* 47 */
struct __attribute__((aligned(2))) city_map_struc
{
  char tile_type;
  char road_type;
  char road_junction[4];
  char road_level_change[4];
  char height;
  char constitution;
  char value;
  char overlaytile_idx;
  char landing_pad;
  char walk_type;
  char voxelIdx[16];
  char has_basement;
  char people_tube_connections[6];
  char mass;
  __int16 strength;
  __int16 damagedtile_idx;
  __int16 supportile_idx;
  char target_Pnt[4];
  __int16 stratmap_idx;
};

/* 48 */
struct __attribute__((aligned(4))) press_button
{
  int calback;
  int img_path;
  int img_aim;
  int x_top;
  int y_top;
  int x_botn;
  int y_botn;
  __int16 img_flag;
  __int16 field_1E;
  int unkn1;
  __int16 scan_keybr;
  __int16 scan_mous_x_1;
  __int16 scan_mous_y_1;
  __attribute__((packed)) __attribute__((aligned(1))) int time_;
  __attribute__((packed)) __attribute__((aligned(1))) int tooltip;
  char press_flag;
  char field_33;
};

/* 49 */
struct __attribute__((aligned(2))) veh_equip_32
{
  __int16 prog_speed;
  __int16 prog_image;
  __int16 damage;
  __int16 accuracy;
  __int16 fire_delay;
  __int16 tail_size;
  __int16 guided;
  __int16 turn_rate;
  __int16 range;
  __int16 projectile_lifetime;
  __int16 horizontal_firing_arc;
  __int16 vertical_firing_arc;
  __int16 point_defence;
  __int16 splits_in_projectile;
  __int16 firing_sound;
  __int16 impact_sound;
  __int16 explosion_graphic;
};

/* 50 */
struct __attribute__((aligned(2))) vehicle_equipment_1
{
  char item_type;
  char effect;
  __int16 item_group;
  __int16 weight;
  __int16 max_ammo_fuel;
  __int16 ammo_fuel_type_used;
  __int16 ammo_fuel_consumptio;
  __int16 picture;
  char size_x;
  char size_y;
  __int16 unknown_11;
  __int16 unknown_12;
  __int16 manufacturer;
  __int16 storage_space_needed;
};

/* 51 */
struct __attribute__((aligned(4))) research_struc
{
  char lab_size_required;
  char item_prerequisite_modifier;
  char tech_prerequisite_modifier;
  char item_prerequisite_group1;
  char item_prerequisite_group2;
  char item_prerequisite_group3;
  __int16 item_prerequisite1;
  __int16 item_prerequisite2;
  __int16 item_prerequisite3;
  __int16 tech_prerequisite_1;
  __int16 tech_prerequisite_2;
  __int16 tech_prerequisite_3;
  __int16 score;
  int skill_hours;
  char research_group;
  char UFOPadia_group;
  __int16 UFOpedia_entry;
};

/* 52 */
struct __attribute__((packed)) __attribute__((aligned(2))) craft_engine_data
{
  int engine_power;
  __int16 top_speed;
};

/* 53 */
struct vehicle_equipment_3_3
{
  __int16 accuracy_modifier;
  __int16 cargo_space;
  __int16 passengers;
  __int16 aliens_held;
  __int16 missile_jamming;
  __int16 shielding;
  __int16 cloaking;
  __int16 teleporting;
  __int16 dimension_shifting;
};

/* 54 */
struct __attribute__((aligned(2))) sound_buff
{
  __int16 num;
  __int16 unknown1;
  __int16 speed;
  __int16 anon3;
  __int16 FFFF_1;
  __int16 x_pos;
  __int16 y_pos;
  __int16 z_pos;
  __int16 FFFF_2;
};

/* 55 */
struct __attribute__((packed)) __attribute__((aligned(2))) manufac_data
{
  __int16 manufacturable;
  int skill_hours;
  __int16 unused1;
  __int16 unused2;
  __int16 tech_prerequisite_modifier;
  __int16 tech_prerequisite_1;
  __int16 tech_prerequisite_2;
  int tech_prerequisite_3;
  char part_need_to_build_item;
  char unused10;
  int unused11;
  __int16 unused12;
  int unused13;
  int unused14;
  int unused15;
  int manufac_cost;
  __int16 item_group;
  __int16 item;
  __int16 lab_size_required;
};

/* 56 */
struct __attribute__((packed)) __attribute__((aligned(2))) market_ctruc
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_stock;
  int last_week_amount_for_sale;
};

/* 57 */
struct __attribute__((packed)) __attribute__((aligned(2))) craft_equip_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 58 */
struct __attribute__((packed)) __attribute__((aligned(2))) amo_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 59 */
struct __attribute__((packed)) __attribute__((aligned(2))) agent_eqv_economics
{
  __int16 available_from_week;
  int base_price;
  __int16 min_stock_increase;
  __int16 max_stock_increase;
  int current_price;
  int current_amount_for_sale;
  int last_week_amount_for_sale;
};

/* 60 */
struct __attribute__((packed)) __attribute__((aligned(2))) funds_init
{
  __int16 race;
  int org_member;
  char Security_level;
  char Security_number;
  int balance;
  int external_income;
  char rebuildrate;
  char like_alien;
};

/* 61 */
struct __attribute__((aligned(4))) facility_data_t
{
  int price;
  char image_offset;
  char fcl_size;
  __int16 day_to_builds;
  __int16 maintainance_cost;
  __int16 capacity;
  char image__;
  char buildable;
  char unused1_fkl;
  char unused2_fkl;
};

/* 62 */
struct __attribute__((aligned(2))) projectile_stru
{
  __int16 weapon_type;
  __int16 prog_image;
  __int16 prog_speed;
  __int16 prog_x_pos[50];
  __int16 prog_y_pos[50];
  __int16 prog_z_pos[50];
  __int16 coord_index;
  __int16 field_134;
  __int16 tail_size_;
  __int16 status;
  __int16 num_aiming_vehicles;
  __int16 dist_3d;
  __int16 x_y_vs_z1_x2;
  __int16 x_y_vs_z2_x2;
  __int16 z_shift_1;
  __int16 z_direct;
  __int16 z_shift_2;
  __int16 direct_3d;
  __int16 distance;
  __int16 anglex2;
  __int16 distx2;
  __int16 r_l_direct;
  __int16 up_down;
  __int16 direct_x;
  __int16 direct_y;
  __int16 lifetime;
  __int16 veh_owner_struc;
  __int16 field_15C;
};

/* 63 */
struct proj_color
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
};

/* 64 */
struct projectile_img
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  char field_22;
  char field_23;
};

/* 65 */
struct __attribute__((aligned(2))) vehicle_equipment_layout
{
  __int16 amount_slots;
  char slot_1_x_pos;
  char slot_1_y_pos;
  char slot_1_x_size;
  char slot_1_y_size;
  char slot_1_type;
  char slot_1_safe_flag;
  char safe_1_x_centr;
  char safe_1_y_centr;
  char slot_2_x_pos;
  char slot_2_y_pos;
  char slot_2_x_size;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  __int16 field_22;
  char field_24;
  char field_25;
  char field_26;
  char field_27;
  char field_28;
  char field_29;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char field_30;
  char field_31;
  char field_32;
  char field_33;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char field_3E;
  char field_3F;
  char field_40;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char field_4E;
  char field_4F;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  char field_5A;
  char field_5B;
  char field_5C;
  char field_5D;
  char field_5E;
  char field_5F;
  char field_60;
  char field_61;
  char field_62;
  char field_63;
  char field_64;
  char field_65;
  char field_66;
  char field_67;
  char field_68;
  char field_69;
  char field_6A;
  char field_6B;
  char field_6C;
  char field_6D;
  char field_6E;
  char field_6F;
  char field_70;
  char field_71;
  char field_72;
  char field_73;
  char field_74;
  char field_75;
  char field_76;
  char field_77;
  char field_78;
  char field_79;
  char field_7A;
  char field_7B;
  __int16 field_7C;
  char field_7E;
  char field_7F;
  char field_80;
  char field_81;
  char field_82;
  char field_83;
  char field_84;
  char field_85;
  char field_86;
  char field_87;
  char field_88;
  char field_89;
  char field_8A;
  char field_8B;
  char field_8C;
  char field_8D;
  char field_8E;
  char field_8F;
  char field_90;
  char field_91;
  char field_92;
  char field_93;
  char field_94;
  char field_95;
  char field_96;
  char field_97;
  char field_98;
  char field_99;
  char field_9A;
  char field_9B;
  char field_9C;
  char field_9D;
  char field_9E;
  char field_9F;
  char field_A0;
  char field_A1;
  char field_A2;
  char field_A3;
  char field_A4;
  char field_A5;
  char field_A6;
  char field_A7;
  char field_A8;
  char field_A9;
  char field_AA;
  char field_AB;
  char field_AC;
  char field_AD;
  char field_AE;
  char field_AF;
  char field_B0;
  char field_B1;
  char field_B2;
  char field_B3;
  char field_B4;
  char field_B5;
  char field_B6;
  char field_B7;
  char field_B8;
  char field_B9;
  char field_BA;
  char field_BB;
  char field_BC;
  char field_BD;
  char field_BE;
  char field_BF;
  char field_C0;
  char field_C1;
  char field_C2;
  char field_C3;
  char field_C4;
  char field_C5;
  char field_C6;
  char field_C7;
  char field_C8;
  char field_C9;
  char field_CA;
  char field_CB;
  char field_CC;
  char field_CD;
  char field_CE;
  char field_CF;
  __int16 field_D0;
  char field_D2;
  char field_D3;
  char field_D4;
  char field_D5;
  char field_D6;
  char field_D7;
  char field_D8;
  char field_D9;
  char field_DA;
  char field_DB;
  char field_DC;
  char field_DD;
  char field_DE;
  char field_DF;
  char field_E0;
  char field_E1;
  char field_E2;
  char field_E3;
  char field_E4;
  char field_E5;
  char field_E6;
  char field_E7;
  char field_E8;
  char field_E9;
  char field_EA;
  char field_EB;
  char field_EC;
  char field_ED;
  char field_EE;
  char field_EF;
  char field_F0;
  char field_F1;
  char field_F2;
  char field_F3;
  char field_F4;
  char field_F5;
  char field_F6;
  char field_F7;
  char field_F8;
  char field_F9;
  char field_FA;
  char field_FB;
  char field_FC;
  char field_FD;
  char field_FE;
  char field_FF;
  char field_100;
  char field_101;
  char field_102;
  char field_103;
  char field_104;
  char field_105;
  char field_106;
  char field_107;
  char field_108;
  char field_109;
  char field_10A;
  char field_10B;
  char field_10C;
  char field_10D;
  char field_10E;
  char field_10F;
  char field_110;
  char field_111;
  char field_112;
  char field_113;
  char field_114;
  char field_115;
  char field_116;
  char field_117;
  char field_118;
  char field_119;
  char field_11A;
  char field_11B;
  char field_11C;
  char field_11D;
  char field_11E;
  char field_11F;
  char field_120;
  char field_121;
  char field_122;
  char field_123;
  char field_124;
  char field_125;
  char field_126;
  char field_127;
  char field_128;
  char field_129;
  char field_12A;
  char field_12B;
  char field_12C;
  char field_12D;
  char field_12E;
  char field_12F;
  char field_130;
  char field_131;
  char field_132;
  char field_133;
  char field_134;
  char field_135;
  char field_136;
  char field_137;
  char field_138;
  char field_139;
  char field_13A;
  char field_13B;
  char field_13C;
  char field_13D;
  char field_13E;
  char field_13F;
  char field_140;
  char field_141;
  char field_142;
  char field_143;
  char field_144;
  char field_145;
  char field_146;
  char field_147;
  char field_148;
  char field_149;
  char field_14A;
  char field_14B;
  char field_14C;
  char field_14D;
  char field_14E;
  char field_14F;
  char field_150;
  char field_151;
  char field_152;
  char field_153;
  char field_154;
  char field_155;
  char field_156;
  char field_157;
  char field_158;
  char field_159;
  char field_15A;
  char field_15B;
  char field_15C;
  char field_15D;
  char field_15E;
  char field_15F;
  char field_160;
  char field_161;
  char field_162;
  char field_163;
  char field_164;
  char field_165;
  char field_166;
  char field_167;
  char field_168;
  char field_169;
};

/* 66 */
struct __attribute__((aligned(4))) unit_score_level
{
  int level_2;
  int level_3;
  int level_4;
  int level_5;
  int level_6;
  int level_7;
  int level_8;
};

/* 67 */
struct __attribute__((aligned(4))) equip_hard_evel
{
  int novice;
  int easy;
  int medium;
  int hard;
  int superhuman;
};

/* 68 */
struct __attribute__((aligned(2))) damage_modif
{
  __int16 smoke;
  __int16 anti_alien_gas;
  __int16 incendiary;
  __int16 stun_gas;
  __int16 explosive;
  __int16 stun;
  __int16 psionic_blast;
  __int16 armor_piercing;
  __int16 laser_beam;
  __int16 plasma;
  __int16 toxin_A;
  __int16 toxin_B;
  __int16 toxin_C;
  __int16 dimesion_destabiliser;
  __int16 disruptor_beam;
  __int16 explosive1;
  __int16 entropy_enzyme;
  __int16 falling_object;
};

/* 69 */
struct __attribute__((aligned(2))) ufopaedia_struct
{
  __int16 group_;
  __int16 entry;
  __int16 pcx_offset;
  __int16 txt_offset;
};

/* 70 */
struct __attribute__((aligned(2))) blding_struc_save
{
  __int16 building_name;
  __int16 x1position;
  __int16 x2position;
  __int16 y1position;
  __int16 y2position;
  __int16 field_A;
  __int16 count_value_zero_tile;
  __int16 x_terminal;
  __int16 y_terminal;
  __int16 z_terminal;
  __int16 ppl_tube_junc_num;
  __int16 ptj_x1;
  __int16 ptj_x2;
  __int16 ptj_x3;
  __int16 ptj_x4;
  __int16 ptj_x5;
  __int16 ptj_x6;
  __int16 ptj_y1;
  __int16 ptj_y2;
  __int16 ptj_y3;
  __int16 ptj_y4;
  __int16 ptj_y5;
  __int16 ptj_y6;
  __int16 ptj_z1;
  __int16 ptj_z2;
  __int16 ptj_z3;
  __int16 ptj_z4;
  __int16 ptj_z5;
  __int16 ptj_z6;
  __int16 linked_bld_count;
  __int16 linked_bld_num1;
  __int16 linked_bld_num2;
  __int16 linked_bld_num3;
  __int16 linked_bld_num4;
  __int16 linked_bld_num5;
  __int16 linked_bld_num6;
  __int16 linked_bld_num7;
  __int16 linked_bld_num8;
  __int16 linked_bld_num9;
  __int16 linked_bld_num10;
  __int16 linked_bld_num11;
  __int16 linked_bld_num12;
  __int16 ppl_t_length_bld_1;
  __int16 ppl_t_length_bld_2;
  __int16 ppl_t_length_bld_3;
  __int16 ppl_t_length_bld_4;
  __int16 ppl_t_length_bld_5;
  __int16 ppl_t_length_bld_6;
  __int16 ppl_t_length_bld_7;
  __int16 ppl_t_length_bld_8;
  __int16 ppl_t_length_bld_9;
  __int16 ppl_t_length_bld_10;
  __int16 ppl_t_length_bld_11;
  __int16 ppl_t_length_bld_12;
  __int16 ppl_tube_junc_con_bld_1;
  __int16 ppl_tube_junc_con_bld_2;
  __int16 ppl_tube_junc_con_bld_3;
  __int16 ppl_tube_junc_con_bld_4;
  __int16 ppl_tube_junc_con_bld_5;
  __int16 ppl_tube_junc_con_bld_6;
  __int16 ppl_tube_junc_con_bld_7;
  __int16 ppl_tube_junc_con_bld_8;
  __int16 ppl_tube_junc_con_bld_9;
  __int16 ppl_tube_junc_con_bld_10;
  __int16 ppl_tube_junc_con_bld_11;
  __int16 ppl_tube_junc_con_bld_12;
  __int16 ppl_tube_junc_con_dir_out_bld_1;
  __int16 ppl_tube_junc_con_dir_out_bld_2;
  __int16 ppl_tube_junc_con_dir_out_bld_3;
  __int16 ppl_tube_junc_con_dir_out_bld_4;
  __int16 ppl_tube_junc_con_dir_out_bld_5;
  __int16 ppl_tube_junc_con_dir_out_bld_6;
  __int16 ppl_tube_junc_con_dir_out_bld_7;
  __int16 ppl_tube_junc_con_dir_out_bld_8;
  __int16 ppl_tube_junc_con_dir_out_bld_9;
  __int16 ppl_tube_junc_con_dir_out_bld_10;
  __int16 ppl_tube_junc_con_dir_out_bld_11;
  __int16 ppl_tube_junc_con_dir_out_bld_12;
  __int16 ppl_tube_conn_to_neig_bld[6];
  __int16 junction;
  __int16 bld_function;
  __int16 bld_type;
  char field_AE;
  char field_AF;
  __int16 field_B0;
  __int16 field_B2;
  __int16 field_B4;
  char purchaseable;
  char field_B7;
  __int16 field_B8;
  __int16 price;
  __int16 alien_detection_timout;
  __int16 fixed_costs;
  __int16 maximum_workforce;
  __int16 current_workforce;
  __int16 current_wage;
  __int16 Income_per_capita;
  char owner;
  char start_base_flag;
  char field_CA;
  char field_CB;
  char $$needed;
  char respect;
  __int16 allow_atac_time;
  __int16 field_D0;
  __int16 field_D2;
  char alien_eggs;
  char brainsuckers;
  char multiworm;
  char hyperworm;
  char chrystali;
  char anthropods;
  char skeletoids;
  char spitter;
  char poppers;
  char megaspawn;
  char psimorphs;
  char quinspawn;
  char micronoid_aggregate;
  char brainsuckers_pods;
};

/* 71 */
struct __attribute__((packed)) __attribute__((aligned(2))) funds_struc_save
{
  __int16 race;
  int org_member;
  char Security_level;
  char Security_number;
  int balance;
  int external_income;
  char rebuildrate;
  char like_alien;
  __int16 combat_value;
  __int16 bld_count;
  int fund_history52;
  int fund_history51;
  int fund_history50;
  int fund_history49;
  int fund_history48;
  int fund_history47;
  int fund_history46;
  int fund_history45;
  int fund_history44;
  int fund_history43;
  int fund_history42;
  int fund_history41;
  int fund_history40;
  int fund_history39;
  int fund_history38;
  int fund_history37;
  int fund_history36;
  int fund_history35;
  int fund_history34;
  int fund_history33;
  int fund_history32;
  int fund_history31;
  int fund_history30;
  int fund_history29;
  int fund_history28;
  int fund_history27;
  int fund_history26;
  int fund_history25;
  int fund_history24;
  int fund_history23;
  int fund_history22;
  int fund_history21;
  int fund_history20;
  int fund_history19;
  int fund_history18;
  int fund_history17;
  int fund_history16;
  int fund_history15;
  int fund_history14;
  int fund_history13;
  int fund_history12;
  int fund_history11;
  int fund_history10;
  int fund_history9;
  int fund_history8;
  int fund_history7;
  int fund_history6;
  int fund_history5;
  int fund_history4;
  int fund_history3;
  int fund_history2;
  int fund_history;
  int funding_history52;
  int funding_history51;
  int funding_history50;
  int funding_history49;
  int field_F6;
  int field_FA;
  int field_FE;
  int field_102;
  int field_106;
  int field_10A;
  int field_10E;
  int field_112;
  int field_116;
  int field_11A;
  int field_11E;
  int field_122;
  int field_126;
  int field_12A;
  int field_12E;
  int field_132;
  int field_136;
  int field_13A;
  int field_13E;
  int field_142;
  int field_146;
  int field_14A;
  int field_14E;
  int field_152;
  int field_156;
  int field_15A;
  int field_15E;
  int field_162;
  int field_166;
  int field_16A;
  int field_16E;
  int field_172;
  int field_176;
  int field_17A;
  int field_17E;
  int field_182;
  int field_186;
  int field_18A;
  int field_18E;
  int field_192;
  int field_196;
  int field_19A;
  int field_19E;
  int field_1A2;
  int field_1A6;
  int field_1AA;
  int field_1AE;
  int cur_funds;
};

/* 72 */
struct __attribute__((aligned(2))) vehicle_init_data
{
  __int16 manufacturer;
  __int16 movement_type_;
  __int16 animation_type_;
  __int16 size_x;
  __int16 size_y;
  __int16 size_z;
  __int16 image_pos_1;
  __int16 image_pos_2;
  __int16 image_pos_3;
  __int16 image_pos_4;
  __int16 image;
  __int16 built_in_accelerat;
  __int16 built_in_unknown;
  __int16 built_in_top_speed;
  __int16 shadow_image;
  __int16 shadow_img_pos_1;
  __int16 shadow_img_pos_2;
  __int16 shadow_img_pos_3;
  __int16 shadow_img_pos_4;
  __int16 loftemps_height;
  __int16 loftemps_index;
  __int16 unknown22;
  __int16 unused23;
  __int16 constitution_;
  __int16 remein_HP_befor_downed;
  __int16 weight_;
  __int16 rear_armor_;
  __int16 top_armor_;
  __int16 right_armor_;
  __int16 left_armor_;
  __int16 under_armor_;
  __int16 front_armor_;
  char passengers_;
  char field_41_;
  __int16 agressivenes;
  __int16 score_veh;
  char equip_layout;
  char equip_layout_image[8];
  char unused38;
  char unknown39;
  char equip_slot[45];
};

/* 73 */
union __attribute__((aligned(8))) __m64
{
  unsigned __int64 m64_u64;
  float m64_f32[2];
  char m64_i8[8];
  __int16 m64_i16[4];
  int m64_i32[2];
  __int64 m64_i64;
  unsigned __int8 m64_u8[8];
  unsigned __int16 m64_u16[4];
  unsigned int m64_u32[2];
};

/* 74 */
union __attribute__((aligned(16))) __m128
{
  float m128_f32[4];
  unsigned __int64 m128_u64[2];
  char m128_i8[16];
  __int16 m128_i16[8];
  int m128_i32[4];
  __int64 m128_i64[2];
  unsigned __int8 m128_u8[16];
  unsigned __int16 m128_u16[8];
  unsigned int m128_u32[4];
};

/* 75 */
struct __m128d
{
  double m128d_f64[2];
};

/* 76 */
union __attribute__((aligned(16))) __m128i
{
  char m128i_i8[16];
  __int16 m128i_i16[8];
  int m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned int m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

/* 77 */
struct __attribute__((aligned(2))) ufo_missions
{
  __int16 ufo_type_1;
  __int16 ufo_type_2;
  __int16 ufo_type_3;
  __int16 ufo_type_1_amount;
  __int16 ufo_type_2_amount;
  __int16 ufo_type_3_amount;
  __int16 ufo_type_1_mission;
  __int16 ufo_type_2_mission;
  __int16 ufo_type_3_mission;
  __int16 ufo_type_1_escorts;
  __int16 ufo_type_2_escorts;
  __int16 ufo_type_3_escorts;
  __int16 field_18;
  char field_1A;
  char field_1B;
  __int16 field_1C;
  __int16 rnd_for_gen_return_coord;
  __int16 field_20;
  __int16 field_22;
  __int16 hit_points_left_before_retreating_setting;
  __int16 field_26;
  __int16 field_28;
};

/* 78 */
struct __attribute__((aligned(2))) ufos_grow
{
  __int16 probe;
  __int16 scout;
  __int16 transport;
  __int16 fast_attack_ship;
  __int16 destroyer;
  __int16 assault_ship;
  __int16 bomber;
  __int16 escort;
  __int16 battleship;
  __int16 mothership;
};

/* 79 */
struct __attribute__((packed)) __attribute__((aligned(1))) unit_equip_set
{
  __int16 weapon_1;
  __int16 clip_type_1;
  __int16 clip_amount_1;
  __int16 weapon_2;
  __int16 clip_type_2;
  __int16 clip_amount_2;
  __int16 weapon_3;
  __int16 clip_type_3;
  __int16 clip_amount_3;
  __int16 weapon_4;
  __int16 clip_type_4;
  __int16 clip_amount_4;
  __int16 weapon_5;
  __int16 clip_type_5;
  __int16 clip_amount_5;
  __int16 weapon_6;
  __int16 clip_type_6;
  __int16 clip_amount_6;
  _BYTE gap24[1];
  __int16 clip_type_7;
  __int16 clip_amount_7;
  __int16 weapon_8;
  __int16 clip_type_8;
  __int16 clip_amount_8;
  __int16 weapon_9;
  __int16 clip_type_9;
  __int16 clip_amount_9;
  __int16 weapon_10;
  __int16 clip_type_10;
  __int16 clip_amount_10;
  __int16 grenade_type_1;
  __int16 grenade_amount_1;
  __int16 grenade_type_2;
  __int16 grenade_amount_2;
  __int16 grenade_type_3;
  __int16 grenade_amount_3;
  __int16 grenade_type_4;
  __int16 grenade_amount_4;
  __int16 grenade_type_5;
  __int16 grenade_amount_5;
  __int16 grenade_type_6;
  __int16 grenade_amount_6;
  __int16 grenade_type_7;
  __int16 grenade_amount_7;
  __int16 grenade_type_8;
  __int16 grenade_amount_8;
  __int16 grenade_type_9;
  __int16 grenade_amount_9;
  __int16 grenade_type_10;
  __int16 grenade_amount_10;
  __int16 other_equip1;
  __int16 other_equip2;
  __int16 other_equip3;
  __int16 other_equip4;
  __int16 other_equip5;
  __int16 other_equip6;
  __int16 other_equip7;
  __int16 other_equip8;
  __int16 other_equip9;
  __int16 other_equip10;
  __int16 other_equip11;
  __int16 other_equip12;
  __int16 other_equip13;
  __int16 other_equip14;
  __int16 other_equip15;
  __int16 other_equip16;
  __int16 other_equip17;
  __int16 other_equip18;
  __int16 other_equip19;
  __int16 other_equip20;
};

/* 80 */
struct __attribute__((aligned(2))) org_names
{
  __int16 org_nm[25];
};

/* 81 */
typedef __iobuf FILE;

/* 82 */
struct __attribute__((aligned(4))) ufo_objects
{
  int portal_home;
  __int16 portal_x_coord_1[10];
  __int16 portal_y_coord_1[10];
  __int16 portal_z_coord_1[10];
  __int16 direction[10];
  __int16 portal_num[10];
  __int16 field_68;
  __int16 field_6A;
  __int16 field_6C;
  __int16 field_6E;
  __int16 field_70;
  char field_72[10];
  char field_7C[10];
  __int16 field_86;
  __int16 field_88;
  __int16 field_8A;
  __int16 prob;
  __int16 scout;
  __int16 transp;
  __int16 fast_ship;
  __int16 destroyer;
  __int16 assault_ship;
  __int16 bomber;
  __int16 escort;
  __int16 battlship;
  __int16 mothership;
  __int16 field_A0[40];
  __int16 field_F0[40];
  __int16 field_140[40];
  __int16 field_190[40];
  __int16 field_1E0[40];
  __int16 field_230[40];
  __int16 field_280[40];
  __int16 field_2D0;
  __int16 field_2D2;
};

/* 83 */
struct __attribute__((aligned(2))) agent_equipment_1
{
  __int16 score;
  char item_type;
  char item_effect;
  __int16 weight;
  __int16 picture;
  char size_x;
  char size_y;
  __int16 manufacturer;
  char storage_space_needed;
  char armor_rating;
  char unknown_11;
  char unknown_12;
  __int16 unused_13;
};

/* 84 */
struct __attribute__((aligned(2))) agent_equipment_2_0
{
  char unused_1;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 unknown_2;
  char armor_position;
  char armor_rating;
  char damage_modifier_type;
  __int16 unknown_6;
  __int16 unused_7;
};

/* 85 */
struct __attribute__((aligned(2))) agent_equipment_2_1
{
  char primary_ammo_effect;
  char secondary_ammo_effect;
  char tertiary_ammo_effect;
  char max_primary_rounds;
  char max_secondary_rounds;
  char max_tertiary_rounds;
  char primary_recharge_speed;
  char secondary_recharge_speed;
  char tertiary_recharge_speed;
  char unused_9;
  char unused_10;
  char unused_11;
  __int16 ammo_type_used;
  __int16 grenade_effect;
};

/* 86 */
struct __attribute__((aligned(2))) agent_equipment_2_2
{
  char ammo_effect;
  char rounds;
  char recharge_speed;
  char unused_3;
  char unused_4;
  char unused_5;
  __int16 unknown_6;
  __int16 ammo_type;
  char item_type;
  char unused_10;
};

/* 87 */
struct __attribute__((aligned(4))) ufo_loudouts
{
  int alien_egg;
  int brainsucker;
  int multiworm;
  int hyperworm;
  int chrysalis;
  int anthropod;
  int skeletoid;
  int spitter;
  int popper;
  int megaspawn;
  int psimorph;
  int queenspawn;
  int micronoid_aggregate;
  int brainsucker_pod;
};

/* 88 */
struct __attribute__((aligned(2))) agent_save_struct
{
  char name[26];
  char count;
  char unk_1;
  char unk_2;
  char unk_3;
  char unk_4;
  char unc_5;
  char unk_6;
  char owned_org;
  char rank;
  char role;
  __int16 agent_base;
  __int16 day_in_servis;
  __int16 kills;
  __int16 missions;
  __int16 Improvement;
  char speed_max_start;
  char health_max_start;
  char stamina_start;
  char reaction_start;
  char strenght_start;
  char braverly_start;
  char accuracy_start;
  char psi_energy_start;
  char psi_attack_start;
  char psi_defece_start;
  char agent_score;
  char teh_role;
  char speed_curr;
  char health_max_curr;
  char health_curr;
  char unc_38;
  char stamina_curr;
  char reaction_cyrr;
  char strenght_curr;
  char braverly_curr;
  char psi_energy_curr;
  char psi_attack_curr;
  char psi_defese_curr;
  char leg_type;
  char accuracy_curr;
  char unc_47;
  char unc_48;
  char bio_skill;
  char qua_skill;
  char eng_skill;
  char unc_52;
  char unc_53;
  char armor_legs;
  char armor_body;
  char armor_left_arm;
  char armor_right_arm;
  char armor_head;
  char armor_back;
  __int16 inventory_id;
  char inventory_id_reference;
  char field_57;
  char field_58;
  char field_59;
  char field_5A;
  char field_5B;
  char field_5C;
  char field_5D;
  char field_5E;
  char field_5F;
  char field_60;
  char field_61;
  __int16 size_x;
  __int16 size_y;
  __int16 field_66;
  char field_67;
  char field_69;
  char field_70;
  char field_6B;
  char field_6C;
  char hired;
  __int16 order;
  __int16 tailing_person;
  char field_72;
  char field_73;
  char field_74;
  char field_75;
  __int16 coord_3d_x;
  __int16 coord_3d_y;
  __int16 coord_3d_z;
  char agent_demension;
  char assignment_type;
  __int16 assignment;
  __int16 target_building;
  __int16 target_bld_num_unk;
  char field_84;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_85;
  char field_87;
  char field_88;
  char field_89;
  char field_8A;
  char field_8B;
  char field_8C;
  char field_8D;
  char field_8E;
  char field_8F;
  char field_90;
  char field_91;
  char field_92;
  char field_93;
  char field_94;
  char field_95;
  char field_96;
  char field_97;
  __int16 field_98;
  __int16 coord_3d_x_1_ikon_bld;
  __int16 coord_3d_y_1_ikon_bld;
  __int16 coord_3d_z_1_ikon_bld;
  __int16 coord_3d_x_2;
  __int16 coord_3d_y_2;
  __int16 coord_3d_z_2;
  char field_A6;
  char field_A7;
  char field_A8;
  char field_A9;
  char field_AA;
  char field_AB;
  char field_AC;
  char field_AD;
  char field_AE;
  char field_AF;
  char hired_flag;
  char field_B1;
  char agent_race;
  char gender;
  char unkn;
  char facial_image;
  char field_B6;
  char field_B7;
  char field_B8;
  char field_B9;
  char field_BA;
  char field_BB;
  char field_BC;
  char field_BD;
  char field_BE;
  char field_BF;
  char field_C0;
  char field_C1;
  char field_C2;
  char field_C3;
  char field_C4;
  char field_C5;
  __int16 assigment_progject;
  char training;
  char field_C9;
  char field_CA;
  char field_CB;
  char field_CC;
  char field_CD;
};

/* 89 */
struct __attribute__((aligned(2))) agent_inventory_struct
{
  __int16 agent;
  char right_hand;
  char left_hend;
  char right_leg;
  char left_leg;
  char right_belt_1;
  char right_belt_2;
  char right_belt_3;
  char right_belt_4;
  char left_belt_1;
  char left_belt_2;
  char left_belt_3;
  char left_belt_4;
  char right_shoulder;
  char left_shoulder;
  char back_pack_1A;
  char back_pack_1B;
  char back_pack_1C;
  char back_pack_1D;
  char back_pack_2A;
  char back_pack_2B;
  char back_pack_2C;
  char back_pack_2D;
  char back_pack_3A;
  char back_pack_3B;
  char back_pack_3C;
  char back_pack_3D;
  char back_pack_4A;
  char back_pack_4B;
  char back_pack_4C;
  char back_pack_4D;
  char back_pack_5A;
  char back_pack_5B;
  char back_pack_5C;
  char back_pack_5D;
  char armor_left_arm;
  char armor_right_arm;
  char armor_body;
  char armor_legs;
  char armor_head;
  char armor_unknown;
  char unknown_42;
  char unknown_43;
  char unknown_44;
  char unknown_45;
  char unknown_46;
  char unknown_47;
  char unknown_48;
  char unknown_49;
  char unknown_50;
  char unknown_51;
  char unknown_52;
  char unknown_53;
  char r_hend_ammo;
  char l_hend_ammo;
  char r_leg_ammo;
  char l_leg_ammo;
  char r_belt_1_ammo;
  char r_belt_2_ammo;
  char r_belt_3_ammo;
  char r_belt_4_ammo;
  char l_belt_1_ammo;
  char l_belt_2_ammo;
  char l_belt_3_ammo;
  char l_belt_4_ammo;
  char r_shoulder_ammo;
  char l_shoulder_ammo;
  char back_pack_1A_ammo;
  char back_pack_1B_ammo;
  char back_pack_1C_ammo;
  char back_pack_1D_ammo;
  char back_pack_2A_ammo;
  char back_pack_2B_ammo;
  char back_pack_2C_ammo;
  char back_pack_2D_ammo;
  char back_pack_3A_ammo;
  char back_pack_3B_ammo;
  char back_pack_3C_ammo;
  char back_pack_3D_ammo;
  char back_pack_4A_ammo;
  char back_pack_4B_ammo;
  char back_pack_4C_ammo;
  char back_pack_4D_ammo;
  char back_pack_5A_ammo;
  char back_pack_5B_ammo;
  char back_pack_5C_ammo;
  char back_pack_5D_ammo;
  char unknown_92;
  char unknown_93;
  char unknown_94;
  char unknown_95;
  char unknown_96;
  char unknown_97;
  char unknown_98;
  char unknown_99;
  char unknown_100;
  char unknown_101;
  char unknown_102;
  char unknown_103;
  char unknown_104;
  char unknown_105;
  char unknown_106;
  char unknown_107;
  char unknown_108;
  char unknown_109;
  char r_hend_weapon_type;
  char l_hend_weapon_type;
  char r_leg_weapon_type;
  char l_leg_weapon_type;
  char r_belt_1_weapon_type;
  char r_belt_2_weapon_type;
  char r_belt_3_weapon_type;
  char r_belt_4_weapon_type;
  char l_belt_1_weapon_type;
  char l_belt_2_weapon_type;
  char l_belt_3_weapon_type;
  char l_belt_4_weapon_type;
  char r_shoulder_weapon_type;
  char l_shoulder_weapon_type;
  char back_pack_1A_weapon_type;
  char back_pack_1B_weapon_type;
  char back_pack_1C_weapon_type;
  char back_pack_1D_weapon_type;
  char back_pack_2A_weapon_type;
  char back_pack_2B_weapon_type;
  char back_pack_2C_weapon_type;
  char back_pack_2D_weapon_type;
  char back_pack_3A_weapon_type;
  char back_pack_3B_weapon_type;
  char back_pack_3C_weapon_type;
  char back_pack_3D_weapon_type;
  char back_pack_4A_weapon_type;
  char back_pack_4B_weapon_type;
  char back_pack_4C_weapon_type;
  char back_pack_4D_weapon_type;
  char back_pack_5A_weapon_type;
  char back_pack_5B_weapon_type;
  char back_pack_5C_weapon_type;
  char back_pack_5D_weapon_type;
  char unknown_140;
  char unknown_141;
  char unknown_142;
  char unknown_143;
  char unknown_144;
  char unknown_145;
  char unknown_146;
  char unknown_147;
  char unknown_148;
  char unknown_149;
  char unknown_150;
  char unknown_151;
  char unknown_152;
  char unknown_153;
  char unknown_154;
  char unknown_155;
  char unknown_156;
  char unknown_157;
};

/* 90 */
struct __attribute__((aligned(2))) vehicle_save_data
{
  __int16 veh_count;
  __int16 movement_type;
  __int16 craft_type;
  char veh_name[42];
  __int16 current_x_pos;
  __int16 current_y_pos;
  __int16 current_altitude;
  __int16 current_frame1;
  __int16 current_frame2;
  __int16 current_frame3;
  __int16 current_frame4;
  __int16 current_frame5;
  __int16 size_x;
  __int16 size_y;
  __int16 size_z;
  __int16 image_pos1;
  __int16 image_pos2;
  __int16 image_pos3;
  __int16 image_pos4;
  __int16 destantion_x_pos;
  __int16 distantion_y_pos;
  __int16 distantion_altitude;
  __int16 altitude_setting;
  __int16 unknown_x_pos1;
  __int16 unknown_y_pos1;
  __int16 unknown_altitude1;
  __int16 current_x_pos_and_size_x;
  __int16 current_y_pos_and_size_y;
  __int16 current_x_pos_and_size_z;
  __int16 veh_path_ind;
  __int16 unknown_29;
  __int16 road_direct_ind;
  __int16 activ_waypoint;
  __int16 unknown_32;
  __int16 vert_direction;
  __int16 speed_x2_div3;
  __int16 hovering_time;
  __int16 unknown_36;
  __int16 unknown_37;
  __int16 unknown_38;
  __int16 unknown_39;
  __int16 unknown_40;
  __int16 unknown_41;
  __int16 waypoint_1_x_pos;
  __int16 waypoint_1_y_pos;
  __int16 waypoint_1_z_pos;
  __int16 waypoint_1_num;
  __int16 waypoint_2_x_pos;
  __int16 waypoint_2_y_pos;
  __int16 waypoint_2_z_pos;
  __int16 waypoint_2_num;
  __int16 waypoint_3_x_pos;
  __int16 waypoint_3_y_pos;
  __int16 waypoint_3_z_pos;
  __int16 waypoint_3_num;
  __int16 waypoint_4_x_pos;
  __int16 waypoint_4_y_pos;
  __int16 waypoint_4_z_pos;
  __int16 waypoint_4_num;
  __int16 waypoint_5_x_pos;
  __int16 waypoint_5_y_pos;
  __int16 waypoint_5_z_pos;
  __int16 waypoint_5_num;
  __int16 waypoint_6_x_pos;
  __int16 waypoint_6_y_pos;
  __int16 waypoint_6_z_pos;
  __int16 waypoint_6_num;
  __int16 waypoint_7_x_pos;
  __int16 waypoint_7_y_pos;
  __int16 waypoint_7_z_pos;
  __int16 waypoint_7_num;
  __int16 waypoint_8_x_pos;
  __int16 waypoint_8_y_pos;
  __int16 waypoint_8_z_pos;
  __int16 waypoint_8_num;
  __int16 unknown_74;
  __int16 unknown_75;
  __int16 unknown_76;
  __int16 unknown_77;
  __int16 unknown_78;
  __int16 unknown_79;
  __int16 unknown_80;
  __int16 unknown_81;
  char active_waypoint;
  char target_type;
  __int16 target_x_pos;
  __int16 target_y_pos;
  char smog_flag;
  char active_waypoints;
  __int16 waypoint1_x_pos;
  __int16 waypoint1_y_pos;
  __int16 waypoint2_x_pos;
  __int16 waypoint2_y_pos;
  __int16 waypoint3_x_pos;
  __int16 waypoint3_y_pos;
  __int16 waypoint4_x_pos;
  __int16 waypoint4_y_pos;
  __int16 waypoint5_x_pos;
  __int16 waypoint5_y_pos;
  __int16 unknown_96;
  __int16 unknown_x_pos3;
  __int16 unknown_y_pos3;
  __int16 unknown_altitude3;
  __int16 unknown_100;
  __int16 anim_speed;
  __int16 anim_frame;
  __int16 unknown_103;
  __int16 unknown_104;
  __int16 Acceleration;
  __int16 Acceleration_2;
  __int16 top_speed;
  __int16 current_speed;
  __int16 unknown_109;
  char field_106;
  char field_107;
  __int16 shadow_struc_offset;
  __int16 veh_assign;
  __int16 unknown_114;
  __int16 unknown_115;
  __int16 lof_height;
  __int16 lof_offset;
  __int16 x_pos_3d;
  __int16 y_pos_3d;
  __int16 z_pos_3d;
  __int16 weapon_slot_1;
  __int16 weapon_slot_2;
  __int16 weapon_slot_3;
  __int16 fire_rate_1;
  __int16 fire_rate_2;
  __int16 fire_rate_3;
  __int16 enable_weapon1;
  __int16 enable_weapon2;
  __int16 enable_weapon3;
  __int16 owner;
  __int16 constitution;
  __int16 unknown_131;
  __int16 max_sheild_points;
  __int16 unknown_133;
  char attack_veh_type_latency[34];
  __int16 target_veh;
  __int16 target_building;
  __int16 veh_mission;
  __int16 unknown_154;
  __int16 unknown_155;
  __int16 unknown_156;
  __int16 unknown_157;
  char rules_of_engag_setting;
  char unk;
  __int16 hit_points_left_before_retreating;
  char return_ufo_flag;
  char field_16B;
  __int16 escorted_type;
  __int16 rnd_for_gen_return_coord;
  char field_170;
  char field_171;
  __int16 unknown_164;
  char current_demention;
  char field_175;
  __int16 weight;
  __int16 unknown_167;
  __int16 current_sheild_point;
  __int16 rear_armor;
  __int16 top_armor;
  __int16 right_armor;
  __int16 left_armor;
  __int16 under_armor;
  __int16 front_armor;
  __int16 unknown_175;
  __int16 accuracy;
  char equipment_layuot;
  char equipment_slot[45];
  __int16 ammo_fuel[45];
  __int16 unk_slot[45];
  char cloaking;
  char frozen;
  char field_270;
  char field_271;
  char field_272;
  char field_273;
  __int16 unknown_292;
};

/* 91 */
struct __attribute__((aligned(2))) agent_equipmen_3
{
  __int16 speed;
  __int16 projectile_image;
  __int16 power;
  __int16 accuracy;
  __int16 fire_delay;
  __int16 unknown_6;
  __int16 guided;
  __int16 tune_rate;
  __int16 range;
  __int16 projectile_lifetime;
  __int16 unknown_11;
  __int16 unknown_12;
  __int16 explosion_graphic;
  __int16 unused14;
  __int16 firing_sound;
  __int16 impact_sound;
  __int16 demage_type;
  __int16 proximity_trigger_type;
  __int16 depletion_rate;
};

/* 92 */
struct loftemps_struc
{
  int width;
  int height;
  int length_masks;
};

/* 93 */
struct __attribute__((aligned(2))) ufo_mission_pattern
{
  __int16 mission_type_1;
  __int16 mission_type_2;
  __int16 mission_type_3;
  __int16 mission_type_4;
  __int16 mission_type_5;
  __int16 mission_type_6;
  __int16 mission_type_7;
  __int16 mission_type_8;
  __int16 mission_type_9;
  __int16 mission_type_10;
};

/* 94 */
struct __attribute__((aligned(2))) color_struc
{
  __int16 r;
  __int16 g;
  __int16 b;
};

/* 95 */
struct __attribute__((aligned(2))) bld_cost
{
  __int16 cost_value;
  __int16 unit_num;
  __int16 incom_value;
  __int16 field_6;
  __int16 money_needed;
  __int16 respect_array;
};

/* 96 */
struct __attribute__((aligned(2))) base_structure
{
  __int16 bld_cnt;
  char base_name[17];
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_13;
  char used_flag_;
  char layout[64];
  char planned_facility[64];
  __int16 vehicle_equip[49];
  __int16 agent_equip[87];
  __int16 fuel_on_base[59];
  __int16 contayment[30];
  __int16 adv_cont[30];
  __int16 unuse_294[20];
  __int16 rain_flag;
};

/* 97 */
struct __attribute__((aligned(2))) junction_struc
{
  __int16 x_pos;
  __int16 y_pos;
  __int16 z_pos;
  __int16 neig_junk_N;
  __int16 neig_junk_E;
  __int16 neig_junk_S;
  __int16 neig_junk_W;
  __int16 distance_N;
  __int16 distance_E;
  __int16 distance_S;
  __int16 distance_W;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  __int16 road_end;
};

/* 98 */
struct __attribute__((packed)) __attribute__((aligned(2))) anim
{
  int z_pos;
  int obj_struc;
  char type_;
  char field_9;
};

/* 99 */
struct __attribute__((aligned(2))) unit_dat_struct
{
  char image;
  char field_1;
  char base_accuracy;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char organiz;
  char field_1F;
  char AI_control;
  char field_21;
  __int16 field_22;
  char field_24;
  char rank;
  char field_26;
  char field_27;
  char score;
  char speed_curr;
  char current_max_speed;
  char stamina_curr;
  char stamina_strt;
  char reaction_cyrr;
  char reaction_start;
  char braverly_curr;
  char psi_energy_curr;
  char psi_energy_strt;
  char psi_attack_start;
  char psi_defece_curr;
  char psi_defece_start;
  char unk23;
  char accuracy_curr;
  char body_armor;
  char uncnown_705;
  char uncnown_704;
  char leg_armor;
  char uncnown_armor;
  char max_speed;
  char field_3D;
  char health_max_curr;
  char field_3F;
  char health_curr;
  char field_41;
  char unk64;
  char field_43;
  __int16 leg_arm;
  __int16 body_arm;
  char larm_armor;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 rarm_armor;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 head_arm;
  char unc_arm;
  char gender;
  char field_4F;
  char l_arm_armor;
  char face_image;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  char field_5A;
  char equip_set_1;
  char equip_set_2;
  char equip_set_3;
  char equip_set_4;
  char equip_set_5;
  char r_arm_armor;
  char field_61;
  __int16 size_x;
  __int16 size_y;
  char unit_type;
  char field_67;
  char move_type_dat;
  char field_69;
  char inventory;
  char strenght_curr;
  char strenght_start;
  char field_6D;
  char field_6E;
  char damage_modifier_group;
  __int16 day_in_servis;
  __int16 kills;
  __int16 missions;
  char unc_7;
  char medals;
  char field_78;
  char field_79;
  __int16 empty_slot_flag;
  __int16 assigment_type;
  __int16 image_position_1;
  __int16 image_position_2;
  __int16 image_position_3;
  __int16 image_position_4;
  char field_86;
  char field_87;
  char speed_3;
  char health_3;
  char stamina_3;
  char reaction_3;
  char strenght_3;
  char braverly_3;
  char accuracy_3;
  char psi_energy_3;
  char psi_attack_3;
  char psi_defece_3;
};

/* 100 */
struct bld_status
{
  __int16 field_0;
  __int16 field_2;
  __int16 field_4;
  __int16 field_6;
  __int16 field_8;
};

/* 101 */
struct __attribute__((aligned(2))) ptang_struc
{
  __int16 pikch_num;
  __int16 x_pos_3d;
  __int16 y_pos_3d;
  __int16 z_pos_3d;
  __int16 speed;
};

/* 102 */
struct raid_table
{
  char field_0;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
};

/* 103 */
struct __attribute__((aligned(4))) raid_loot
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_34;
  int field_38;
};

/* 104 */
struct __attribute__((aligned(2))) engagment_struc
{
  char field_eng_0;
  char attack_dist;
  char attack_dist_array[34];
  char attack_setting;
  char field_25_[34];
  char retriat;
  char retriat_array[34];
  char field_6A_;
  char field_6B[34];
  char field_8D;
  __int16 fiel_8E;
  __int16 eng_mission;
  __int16 points_before_retreating;
};

/* 105 */
struct __attribute__((aligned(2))) agent_path_struc
{
  __int16 field_0;
  __int16 field_1;
};

/* 106 */
struct __attribute__((aligned(2))) tube_connection_tile
{
  __int16 x;
  __int16 y;
  __int16 z;
};

/* 107 */
struct spotted_alien_blding
{
  char bld_status;
  char unit_in_bld;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
};

/* 108 */
struct __attribute__((packed)) __attribute__((aligned(2))) reserch
{
  char reserch_flag;
  char agent_base;
  __int16 assigment_progject;
  int skill_hours;
  __int16 researched;
};

/* 109 */
struct __attribute__((aligned(2))) organized_crime
{
  __int16 organization;
  __int16 action_type;
  __int16 target_building;
  __int16 time;
};

/* 110 */
struct __attribute__((aligned(2))) start_facilities_struc
{
  __int16 facility_1;
  __int16 facility_2;
  __int16 facility_3;
  __int16 facility_4;
  __int16 facility_5;
  __int16 facility_6;
  __int16 facility_7;
  __int16 facility_8;
  __int16 facility_9;
  __int16 facility_10;
  __int16 facility_11;
  __int16 facility_12;
  __int16 facility_13;
};

/* 111 */
struct base_layout_struc
{
  char row_1_tile_1;
  char row_1_tile_2;
  char row_1_tile_3;
  char row_1_tile_4;
  char row_1_tile_5;
  char row_1_tile_6;
  char row_1_tile_7;
  char row_1_tile_8;
  char row_2_tile_1;
  char row_2_tile_2;
  char row_2_tile_3;
  char row_2_tile_4;
  char row_2_tile_5;
  char row_2_tile_6;
  char row_2_tile_7;
  char row_2_tile_8;
  char row_3_tile_1;
  char row_3_tile_2;
  char row_3_tile_3;
  char row_3_tile_4;
  char row_3_tile_5;
  char row_3_tile_6;
  char row_3_tile_7;
  char row_3_tile_8;
  char row_4_tile_1;
  char row_4_tile_2;
  char row_4_tile_3;
  char row_4_tile_4;
  char row_4_tile_5;
  char row_4_tile_6;
  char row_4_tile_7;
  char row_4_tile_8;
  char row_5_tile_1;
  char row_5_tile_2;
  char row_5_tile_3;
  char row_5_tile_4;
  char row_5_tile_5;
  char row_5_tile_6;
  char row_5_tile_7;
  char row_5_tile_8;
  char row_6_tile_1;
  char row_6_tile_2;
  char row_6_tile_3;
  char row_6_tile_4;
  char row_6_tile_5;
  char row_6_tile_6;
  char row_6_tile_7;
  char row_6_tile_8;
  char row_7_tile_1;
  char row_7_tile_2;
  char row_7_tile_3;
  char row_7_tile_4;
  char row_7_tile_5;
  char row_7_tile_6;
  char row_7_tile_7;
  char row_7_tile_8;
  char row_8_tile_1;
  char row_8_tile_2;
  char row_8_tile_3;
  char row_8_tile_4;
  char row_8_tile_5;
  char row_8_tile_6;
  char row_8_tile_7;
  char row_8_tile_8;
};

/* 112 */
struct unk_armor_struc
{
  char ttt;
  char x_pos1;
  char y_pos1;
  char x_pos2;
  char y_pos2;
  char armor_pos;
  char field_6;
  char field_7;
};

/* 113 */
struct __attribute__((aligned(2))) veh_shadow_struc
{
  __int16 shadow_image;
  __attribute__((packed)) __attribute__((aligned(1))) int current_frame1;
  __attribute__((packed)) __attribute__((aligned(1))) int current_frame3;
  __int16 tile;
  __int16 shadow_image_pos_3;
  __int16 shadow_image_pos_4;
  __int16 shadow_image_pos_1;
  __int16 shadow_image_pos_2;
  __int16 animation_type;
  __int16 current_x_pos;
  __int16 current_y_pos;
  __int16 current_altitude;
  __int16 road_direct_ind;
  __int16 activ_waypoint;
};

/* 114 */
struct __attribute__((aligned(4))) agent_recovery_struc
{
  int medical;
  int trainning;
  int psi;
};

/* 115 */
struct __attribute__((aligned(4))) agent_in_facility_struc
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int medical_bay_count;
  int wounded_agents;
  int trainning_aria_count;
  int trainning_agents;
  int psi_gum_count;
  int psi_training_agents;
  int field_38;
  int field_3C;
  int field_40;
  int field_44;
  int field_48;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
  int field_68;
  int field_6C;
  int field_70;
  int field_74;
  int field_78;
  int field_7C;
  int field_80;
  int field_84;
  int field_88;
  int field_8C;
};

/* 116 */
struct __attribute__((aligned(2))) colapse_tile_struc
{
  __int16 col_flag;
  __int16 x_value;
  __int16 y_value;
  __int16 z_value;
};

/* 117 */
struct __attribute__((aligned(4))) unit_equipset_builtin
{
  int weapon_type1;
  int appearance_chance;
  int clip_type;
  int clip_amount;
  int weapon_type2;
  int appearance_weap2;
  int clip_type2;
  int clip_amount2;
  int equipment_type1;
  int appearance_eq1;
  int equip1_emount;
  int equipment_type2;
  int appearance_eq2;
  int equip2_emount;
  int equipment_type3;
  int appearance_eq3;
  int equip3_emount;
  int equipment_type4;
  int appearance_eq4;
  int equip4_emount;
  int equipment_type5;
  int appearance_eq5;
  int equip5_emount;
};

/* 118 */
struct __attribute__((aligned(2))) main_interf_tab_selection
{
  __int16 field_0;
  __int16 base_tab;
  __int16 veh_tab;
  __int16 agent_tab;
  __int16 bio_tab;
  __int16 eng_tab;
  __int16 qua_tab;
  __int16 ufo_tab;
  __int16 field_10;
  __int16 field_12;
  __int16 field_14;
};

/* 119 */
struct __attribute__((aligned(2))) veh_land_struc
{
  __int16 veh_num;
  __int16 base;
  __int16 direction;
  __int16 z_level_pod;
};

/* 120 */
struct __attribute__((aligned(4))) manufacturing_struc
{
  char base_number;
  char progect_num;
  __int16 item_name;
  int total_number;
  int completed_item_num;
  int current_skill_hour;
};

/* 121 */
struct __attribute__((aligned(4))) map_size_struct
{
  int x_size_0;
  int y_size_0;
  int z_size_0;
  int x_size_1;
  int y_size_1;
  int z_size_1;
  int x_size_2;
  int y_size_2;
  int z_size_2;
  int x_size_3;
  int y_size_3;
  int z_size_3;
};

/* 122 */
struct __attribute__((packed)) __attribute__((aligned(1))) building_dat_ctruc
{
  int base_map_size_x;
  int base_map_size_y;
  int base_map_size_z;
  int sizes_map_block_x;
  int sizes_map_block_y;
  int sizes_map_block_z;
  char entrance_NESW;
  char exit_NESW;
  int min_entrance_levels;
  int max_entrance_levels;
  int min_exit_levels;
  int max_exit_levels;
  char max_entrance_levels_[1919];
  int ind_destroyed_ground_tile;
};

/* 123 */
struct __attribute__((aligned(4))) SDT_struc
{
  int x_size;
  int y_size;
  int z_size;
  int min_value;
  int max_value;
};

/* 124 */
struct __attribute__((packed)) __attribute__((aligned(1))) losarea_dat_struc
{
  __int16 uncn;
  __int16 x1;
  __int16 y1;
  __int16 z1;
  __int16 x2;
  __int16 y2;
  __int16 z2;
  char field_E[58];
  char not_data[57];
  char AI_Patrol_Priority;
  char AI_Target_Priority;
  char Spawn_Type;
  char Spawn_Priority;
  char Can_Deploy_Large_Units;
  char Can_Deploy_Non_Flying_Units;
};

/* 125 */
struct object_dat_struc
{
  char owned_org;
  char score;
  char equipment;
  char unit_num;
  char x_coord;
  char y_coord;
  char z_coord;
  char field_7;
  char field_8;
  char field_9;
  char max_primary_rounds;
  char field_B;
  char primary_ammo_effect;
  char field_D;
  char armor_rating;
  char field_F;
  char field_10;
  char field_11;
  char orgs[28];
  char owned_org_;
  char field_2F;
};

/* 126 */
struct save_name_struct
{
  char field_0[81];
};

/* 127 */
struct main_interf_tab_sub_selection
{
};

/* 128 */
struct struc_116
{
};

/* 129 */
struct struc_117
{
  __int16 field_0;
  __int16 field_2;
  __int16 field_4;
  __int16 field_6;
  __int16 field_8;
  __int16 field_A;
  __int16 field_C;
  __int16 field_E;
  __int16 field_10;
  __int16 field_12;
  __int16 field_14;
};

/* 130 */
struct sqreen_struc
{
  __int16 used_flag;
  __int16 size_x;
  __int16 size_y;
  __int16 size_z;
  __int16 delta_x_down;
  __int16 delta_x_up;
  __int16 delta_y_down;
  __int16 delta_y_up;
};

/* 131 */
struct falling_tile_struc
{
  char x_value;
  char y_value;
  char z_value;
  char tile_count;
  char field_4;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  char field_9;
  char field_A;
  char field_B;
  char field_C;
  char field_D;
  char field_E;
  char field_F;
  char field_10;
  char field_11;
  char field_12;
  char field_13;
  char field_14;
  char field_15;
  char field_16;
  char field_17;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  char constitution;
  char field_1D;
  char field_1E;
  char field_1F;
  char mass;
  char field_21;
};

/* 132 */
struct __attribute__((aligned(2))) tile_dem_ind_struc
{
  __int16 used_flag;
  __int16 x_coord[64];
  __int16 y_coord[64];
  __int16 z_coord[64];
};

/* 133 */
struct __attribute__((packed)) __attribute__((aligned(2))) log_history_struc
{
  int count;
  char field_4;
  char field_5;
  __int16 year;
  __int16 month;
  __int16 day;
  __int16 hour;
  __int16 minute;
  __int16 second;
  __int16 x_pos;
  __int16 y_pos;
  __int16 z_pos;
  char text[55];
  char field_4F;
  char alien_demen_flag;
  char field_51;
};

/* 134 */
struct __attribute__((aligned(2))) cargo_item
{
  __int16 vehicle;
  __int16 item;
  __int16 amount;
  char item_type;
  char field_7;
};

/* 135 */
struct __attribute__((aligned(2))) unit_select_stru
{
  __int16 unit;
  __attribute__((packed)) __attribute__((aligned(1))) int unit_pointer;
  char type_1;
  char field_7;
};

/* 136 */
struct spotted_alien_bld_struc
{
  __int16 type_occurrences;
  __int16 unit_1;
  __int16 field_4;
  __int16 unit_2;
  __int16 field_8;
};

/* 137 */
struct __attribute__((aligned(4))) scenario_dat
{
  char map_name[40];
  int total_tac_map_x_size;
  int total_tac_map_y_size;
  int total_tac_map_z_size;
  int game_type;
  int xcom_mission_type;
  int year_tac;
  int month_tac;
  int week__tac;
  int day_tac;
  int hour_tac;
  int minute_tac;
  int second_tac;
  int bldn_num;
  int bld_function_sc;
  int bld_owner_sc;
  int bld_relation;
  int field_6A;
  int field_6C;
  int field_70;
  int field_74;
  int bld_ship_type_mission;
  char rank_sum[7];
  char field_83;
  int field_84;
  int field_88;
  int field_8C;
  int field_90;
  int field_94;
  int field_98;
  int field_9C;
  int field_A0;
  int field_A4;
  int field_A8;
  int diff_enum;
  int field_B0;
  int field_B4;
  int tac_score;
  int field_BC;
  char field_C0;
  char field_C1;
  char field_C2;
  char field_C3;
  int field_C4;
  int field_C8;
  int field_CC;
  int field_D0;
};

/* 138 */
struct __attribute__((aligned(2))) agent_init_struc
{
  char score;
  char max_score_incr;
  char base_speed;
  char max_speed_icr;
  __int16 base_health;
  __int16 max_health_icr;
  char unk7;
  char unk8;
  char base_stamina;
  char max_stamina_icr;
  char base_reactions;
  char max_reactions_icr;
  char base_strenght;
  char max_strenght_icr;
  char base_braverly;
  char max_braverly_icr;
  char base_psi_energy;
  char max_psi_energy_icr;
  char base_psi_attack;
  char max_psi_attack_icr;
  char base_psi_defence;
  char max_psi_defence_icr;
  char unk22;
  char unk23;
  char base_accuracy;
  char max_accuracy_icr;
  char field_28;
  char field_30_;
  char field_31;
  char field_32_;
  char bio_skill;
  char max_bio_skill_increace;
  char qua_skill;
  char max_qua_skill_increace;
  char eng_skill;
  char max_eng_skill_increace;
  char field_38;
  char field_39;
  char field_40;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  char field_54;
  char field_55;
  char field_56;
  char field_57;
  char field_58;
  char field_59;
  __int16 size_x;
  __int16 size_y;
  __int16 unit_type;
  char movement_type;
  char field_67;
  char inventory;
  char leg_type;
  __int16 head_armor;
  __int16 body_armor;
  __int16 r_arm_armor;
  __int16 l_arm_armor;
  __int16 leg_armor;
  __int16 unk_armor;
  char unknown_71;
  char equipment_set_1;
  char equipment_set_2;
  char equipment_set_3;
  char equipment_set_4;
  char equipment_set_5;
  char field_583;
  char armor_back;
  __int16 unknown_78;
  __int16 empty_slot_flag;
  char assigment_type;
  char field_5F;
  __int16 image_position_1;
  __int16 image_position_2;
  __int16 image_position_3;
  __int16 image_position_4;
  __int16 image;
};

/* 140 */
struct l_name
{
  char field_0[12];
};

/* 141 */
struct f_name
{
  char field_0[11];
};

/* 142 */
struct manuf_data
{
};

/* 143 */
struct sound_strucure
{
};

/* 144 */
struct __attribute__((packed)) __attribute__((aligned(2))) music_stuct
{
  __int16 field_0;
  __int16 group_number;
  __int16 field_4;
  int track_number;
};

/* 145 */
struct veh_path_struc
{
  void *x_value;
  __int16 z_value;
  __int16 vaypoint_;
};

